import { readFileSync } from 'node:fs';
import path from 'node:path';

const { colorVariableDeclarations, hexToChannels } = require('../../../tailwind.theme.cjs');

/**
 * `globals.css` and `src/theme/palette.js` must state the same colours.
 *
 * Phase 0 of the redesign collapsed four copies of the palette into one
 * authored source (`palette.js`) and pointed Tailwind's colour map at CSS
 * variables. That leaves exactly TWO representations of each hex: the JS object
 * and the `--c-*` declarations in globals.css. Two is not one, and the reason is
 * structural — globals.css is plain CSS with no build step, so the block cannot
 * be generated into it, while `theme/chartConfig.ts` hands literal colours to
 * recharts at runtime and cannot read a CSS variable under SSR or jsdom.
 *
 * So the second copy is generated by `colorVariableDeclarations()` and pinned
 * here. If someone edits one side, this fails and names the line. That is the
 * difference between "we wrote it down twice and hoped" and "it cannot drift".
 *
 * If this test fails after a deliberate palette change, do not edit the
 * expectation — run the generator and paste its output into globals.css:
 *   node -e "console.log(require('./web/tailwind.theme.cjs').colorVariableDeclarations())"
 */
const GLOBALS = readFileSync(path.join(__dirname, '..', '..', 'app', 'globals.css'), 'utf8');

const BEGIN = '/* >>> generated: palette scale, see tailwind.theme.cjs <<< */';
const END = '/* <<< end generated palette scale >>> */';

describe('globals.css colour variables', () => {
  it('carries the generated block, delimited so it can be regenerated', () => {
    expect(GLOBALS).toContain(BEGIN);
    expect(GLOBALS).toContain(END);
    expect(GLOBALS.indexOf(BEGIN)).toBeLessThan(GLOBALS.indexOf(END));
  });

  it('declares exactly what the palette derives, in the same order', () => {
    const block = GLOBALS.slice(GLOBALS.indexOf(BEGIN) + BEGIN.length, GLOBALS.indexOf(END));
    const declared = block
      .split('\n')
      .map((l) => l.trim())
      .filter((l) => l.startsWith('--c-'));
    const expected = colorVariableDeclarations('')
      .split('\n')
      .map((l) => l.trim());
    expect(declared).toEqual(expected);
  });

  it('converts hex to channels correctly', () => {
    // A control with a known answer, so a broken converter cannot make the
    // comparison above pass by agreeing with itself.
    expect(hexToChannels('#00E5A0')).toBe('0 229 160');
    expect(hexToChannels('#ffffff')).toBe('255 255 255');
    expect(hexToChannels('#000')).toBe('0 0 0');
    expect(() => hexToChannels('rgba(0,0,0,.5)')).toThrow();
  });
});
