/**
 * Upgraded Corporate & Education Templates
 * Design system: Google Fonts (Inter + Playfair Display), rich gradients,
 * CSS Grid, box-shadows, pseudo-elements, min 2.5vw body / 5vw headings
 */

import { TemplateSeed } from './template-seeds';

const fontsImport = `@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');`;

const baseReset = `*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden;-webkit-font-smoothing:antialiased}`;

// ============================================================================
// CORPORATE TEMPLATES (12)
// ============================================================================
export const corporateTemplates: TemplateSeed[] = [
  {
    name: 'Company Announcement',
    description: 'Professional company-wide announcement with elegant gradient and decorative accent line',
    category: 'corporate',
    libraryTags: ['announcement', 'internal', 'news'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    isFeatured: true,
    templateHtml: `<style>${fontsImport}${baseReset}.announce{height:100vh;background:linear-gradient(135deg,#0a1628 0%,#1a365d 40%,#2563eb 100%);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;padding:8vw;position:relative;overflow:hidden}.announce::before{content:'';position:absolute;top:0;left:50%;transform:translateX(-50%);width:12vw;height:0.4vh;background:linear-gradient(90deg,transparent,#60a5fa,#93c5fd,#60a5fa,transparent);border-radius:2px}.announce::after{content:'';position:absolute;bottom:0;left:50%;transform:translateX(-50%);width:12vw;height:0.4vh;background:linear-gradient(90deg,transparent,#60a5fa,#93c5fd,#60a5fa,transparent);border-radius:2px}.announce .inner{max-width:75vw}.announce h1{font-family:'Playfair Display',serif;font-size:5.5vw;font-weight:900;margin-bottom:3.5vh;line-height:1.15;letter-spacing:-0.02em;text-shadow:0 2px 20px rgba(0,0,0,0.3)}.announce p{font-size:2.8vw;line-height:1.7;opacity:0.92;font-weight:300;letter-spacing:0.01em}</style><div class="announce"><div class="inner"><h1>{{title}}</h1><p>{{message}}</p></div></div>`,
    sampleData: { title: 'Company Town Hall', message: 'Join us this Friday at 3 PM in the main conference room for our quarterly update.' },
  },
  {
    name: 'KPI Dashboard',
    description: 'Dark ops-style KPI dashboard with 4 metric cards, colored top borders, and subtle grid lines',
    category: 'corporate',
    libraryTags: ['kpi', 'metrics', 'dashboard'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 30,
    isFeatured: true,
    templateHtml: `<style>${fontsImport}${baseReset}.kpi{height:100vh;background:#0f172a;color:#fff;padding:3.5vw;display:flex;flex-direction:column;background-image:linear-gradient(rgba(255,255,255,0.03) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,0.03) 1px,transparent 1px);background-size:4vw 4vw}.kpi h1{font-family:'Inter',sans-serif;font-size:5vw;font-weight:800;text-align:center;margin-bottom:4vh;background:linear-gradient(135deg,#60a5fa,#a78bfa);-webkit-background-clip:text;-webkit-text-fill-color:transparent;letter-spacing:-0.02em}.kpi .grid{display:grid;grid-template-columns:repeat(4,1fr);gap:2vw;flex:1}.kpi .card{background:linear-gradient(145deg,#1e293b,#1a2332);border-radius:16px;padding:3vw;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;box-shadow:0 4px 24px rgba(0,0,0,0.3),inset 0 1px 0 rgba(255,255,255,0.05);position:relative;overflow:hidden}.kpi .card::before{content:'';position:absolute;top:0;left:0;right:0;height:4px;border-radius:16px 16px 0 0}.kpi .card:nth-child(1)::before{background:linear-gradient(90deg,#22c55e,#4ade80)}.kpi .card:nth-child(2)::before{background:linear-gradient(90deg,#22c55e,#4ade80)}.kpi .card:nth-child(3)::before{background:linear-gradient(90deg,#22c55e,#4ade80)}.kpi .card:nth-child(4)::before{background:linear-gradient(90deg,#ef4444,#f87171)}.kpi .card .value{font-size:5vw;font-weight:900;margin-bottom:1vh;letter-spacing:-0.03em}.kpi .card:nth-child(1) .value,.kpi .card:nth-child(2) .value,.kpi .card:nth-child(3) .value{color:#60a5fa}.kpi .card:nth-child(4) .value{color:#f87171}.kpi .card .label{font-size:1.6vw;opacity:0.6;text-transform:uppercase;letter-spacing:0.12em;font-weight:500;margin-bottom:1.2vh}.kpi .card .change{font-size:1.8vw;font-weight:700;padding:0.5vh 1.2vw;border-radius:6px}.kpi .card:nth-child(1) .change,.kpi .card:nth-child(2) .change,.kpi .card:nth-child(3) .change{color:#4ade80;background:rgba(34,197,94,0.12)}.kpi .card:nth-child(4) .change{color:#f87171;background:rgba(239,68,68,0.12)}</style><div class="kpi"><h1>{{title}}</h1><div class="grid"><div class="card"><div class="value">{{metric1Value}}</div><div class="label">{{metric1Label}}</div><div class="change">{{metric1Change}}</div></div><div class="card"><div class="value">{{metric2Value}}</div><div class="label">{{metric2Label}}</div><div class="change">{{metric2Change}}</div></div><div class="card"><div class="value">{{metric3Value}}</div><div class="label">{{metric3Label}}</div><div class="change">{{metric3Change}}</div></div><div class="card"><div class="value">{{metric4Value}}</div><div class="label">{{metric4Label}}</div><div class="change">{{metric4Change}}</div></div></div></div>`,
    sampleData: { title: 'Q1 Performance', metric1Value: '$2.4M', metric1Label: 'Revenue', metric1Change: '+12%', metric2Value: '94%', metric2Label: 'Customer Satisfaction', metric2Change: '+3%', metric3Value: '1,247', metric3Label: 'New Customers', metric3Change: '+18%', metric4Value: '4.2%', metric4Label: 'Churn Rate', metric4Change: '+0.3%' },
  },
  {
    name: 'Meeting Room Schedule',
    description: 'Clean white meeting room display with status badge, alternating row colors, and refined table',
    category: 'corporate',
    libraryTags: ['meeting', 'room', 'schedule'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 60,
    templateHtml: `<style>${fontsImport}${baseReset}.room{height:100vh;background:linear-gradient(180deg,#f8fafc 0%,#f1f5f9 100%);padding:3.5vw;display:flex;flex-direction:column}.room h1{font-family:'Inter',sans-serif;font-size:5vw;font-weight:800;color:#0f172a;margin-bottom:1.5vh;letter-spacing:-0.02em}.room .status{font-size:2.5vw;margin-bottom:3.5vh;padding:1.2vh 2.5vw;border-radius:10px;display:inline-block;font-weight:700;letter-spacing:0.02em;box-shadow:0 2px 8px rgba(0,0,0,0.08)}.room .available{background:linear-gradient(135deg,#22c55e,#16a34a);color:#fff}.room .occupied{background:linear-gradient(135deg,#ef4444,#dc2626);color:#fff}.room .schedule{border-collapse:collapse;width:100%;font-size:2.5vw;flex:1;border-radius:12px;overflow:hidden;box-shadow:0 4px 16px rgba(0,0,0,0.06)}.room .schedule th{background:#1e293b;padding:2vh 2.5vw;text-align:left;color:#e2e8f0;font-weight:600;letter-spacing:0.04em;text-transform:uppercase;font-size:1.8vw}.room .schedule td{padding:2vh 2.5vw;border-bottom:1px solid #e2e8f0;color:#334155}.room .schedule tr:nth-child(even) td{background:#f8fafc}.room .schedule tr:nth-child(odd) td{background:#fff}.room .schedule tr:hover td{background:#eff6ff}</style><div class="room"><h1>{{roomName}}</h1><div class="status {{statusClass}}">{{statusText}}</div><table class="schedule"><tr><th>Time</th><th>Meeting</th><th>Organizer</th></tr><tr><td>{{time1}}</td><td>{{meeting1}}</td><td>{{org1}}</td></tr><tr><td>{{time2}}</td><td>{{meeting2}}</td><td>{{org2}}</td></tr><tr><td>{{time3}}</td><td>{{meeting3}}</td><td>{{org3}}</td></tr></table></div>`,
    sampleData: { roomName: 'Conference Room A', statusClass: 'available', statusText: 'Available', time1: '9:00 - 10:00', meeting1: 'Sprint Planning', org1: 'J. Smith', time2: '11:00 - 12:00', meeting2: 'Design Review', org2: 'A. Chen', time3: '2:00 - 3:00', meeting3: 'Client Call', org3: 'M. Johnson' },
  },
  {
    name: 'Employee Spotlight',
    description: 'Deep blue gradient employee feature with circular avatar placeholder, initials, and elegant italic quote',
    category: 'corporate',
    libraryTags: ['employee', 'recognition', 'culture'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${fontsImport}${baseReset}.spotlight{height:100vh;background:linear-gradient(160deg,#0c1a3a 0%,#1e3a6e 50%,#2a4a8e 100%);color:#fff;display:flex;align-items:center;justify-content:center;padding:5vw;position:relative;overflow:hidden}.spotlight::before{content:'';position:absolute;top:-20vh;right:-10vw;width:50vw;height:50vw;border-radius:50%;background:radial-gradient(circle,rgba(96,165,250,0.08),transparent 70%)}.spotlight .content{display:flex;align-items:center;gap:5vw}.spotlight .avatar{width:18vw;height:18vw;border-radius:50%;background:linear-gradient(135deg,#3b82f6,#8b5cf6);display:flex;align-items:center;justify-content:center;font-size:7vw;font-weight:800;letter-spacing:0.05em;box-shadow:0 8px 32px rgba(59,130,246,0.3);flex-shrink:0;border:4px solid rgba(255,255,255,0.15)}.spotlight .info{text-align:left}.spotlight .label{font-size:2.5vw;color:#93c5fd;font-weight:600;text-transform:uppercase;letter-spacing:0.12em;margin-bottom:1.5vh}.spotlight h1{font-family:'Playfair Display',serif;font-size:5.5vw;font-weight:900;margin-bottom:1.5vh;letter-spacing:-0.01em}.spotlight .title{font-size:2.5vw;opacity:0.75;margin-bottom:3vh;font-weight:300}.spotlight .quote{font-family:'Playfair Display',serif;font-size:2.8vw;font-style:italic;line-height:1.6;opacity:0.9;border-left:3px solid #60a5fa;padding-left:2vw}</style><div class="spotlight"><div class="content"><div class="avatar">{{initials}}</div><div class="info"><div class="label">Employee of the Month</div><h1>{{name}}</h1><div class="title">{{jobTitle}}</div><div class="quote">"{{quote}}"</div></div></div></div>`,
    sampleData: { name: 'Maria Rodriguez', initials: 'MR', jobTitle: 'Senior Engineer — Platform Team', quote: 'Exceeded all sprint goals and mentored 3 junior developers this quarter.' },
  },
  {
    name: 'Safety Metrics',
    description: 'Bold green gradient with massive day counter and progress-bar decoration',
    category: 'corporate',
    libraryTags: ['safety', 'metrics', 'workplace'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>${fontsImport}${baseReset}.safety{height:100vh;background:linear-gradient(160deg,#064e3b 0%,#059669 50%,#34d399 100%);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;position:relative;overflow:hidden}.safety::before{content:'';position:absolute;bottom:8vh;left:50%;transform:translateX(-50%);width:70vw;height:1.2vh;background:rgba(255,255,255,0.15);border-radius:1vh}.safety::after{content:'';position:absolute;bottom:8vh;left:15%;width:50vw;height:1.2vh;background:linear-gradient(90deg,#a7f3d0,#6ee7b7,#34d399);border-radius:1vh;box-shadow:0 0 20px rgba(167,243,208,0.4)}.safety .inner{position:relative;z-index:1}.safety h1{font-family:'Inter',sans-serif;font-size:5vw;font-weight:800;margin-bottom:4vh;text-transform:uppercase;letter-spacing:0.08em;text-shadow:0 2px 12px rgba(0,0,0,0.2)}.safety .big{font-size:14vw;font-weight:900;margin:2vh 0;line-height:1;letter-spacing:-0.04em;text-shadow:0 4px 24px rgba(0,0,0,0.15)}.safety .label{font-size:3vw;opacity:0.92;font-weight:500;letter-spacing:0.04em}.safety .sub{font-size:2.5vw;margin-top:4vh;opacity:0.8;font-weight:300}</style><div class="safety"><div class="inner"><h1>{{title}}</h1><div class="big">{{days}}</div><div class="label">{{label}}</div><div class="sub">{{subtext}}</div></div></div>`,
    sampleData: { title: 'Safety First', days: '247', label: 'Days Without Incident', subtext: 'Keep up the great work!' },
  },
  {
    name: 'Company Values',
    description: 'Clean white 3-column value cards with large emoji icons and subtle shadows',
    category: 'corporate',
    libraryTags: ['values', 'culture', 'mission'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 25,
    templateHtml: `<style>${fontsImport}${baseReset}.values{height:100vh;background:linear-gradient(180deg,#ffffff 0%,#f8fafc 100%);padding:5vw;display:flex;flex-direction:column;justify-content:center}.values h1{font-family:'Playfair Display',serif;font-size:5vw;font-weight:900;text-align:center;color:#0f172a;margin-bottom:5vh;letter-spacing:-0.02em}.values .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:3vw}.values .value{text-align:center;padding:4vw 3vw;background:#fff;border-radius:20px;box-shadow:0 4px 24px rgba(0,0,0,0.06),0 1px 3px rgba(0,0,0,0.04);transition:transform 0.3s}.values .value .icon{font-size:5vw;margin-bottom:2.5vh;display:block}.values .value h3{font-family:'Inter',sans-serif;font-size:2.8vw;font-weight:700;color:#0f172a;margin-bottom:1.5vh}.values .value p{font-size:2.5vw;color:#64748b;line-height:1.6;font-weight:400}</style><div class="values"><h1>Our Values</h1><div class="grid"><div class="value"><span class="icon">{{icon1}}</span><h3>{{value1}}</h3><p>{{desc1}}</p></div><div class="value"><span class="icon">{{icon2}}</span><h3>{{value2}}</h3><p>{{desc2}}</p></div><div class="value"><span class="icon">{{icon3}}</span><h3>{{value3}}</h3><p>{{desc3}}</p></div></div></div>`,
    sampleData: { icon1: '💡', value1: 'Innovation', desc1: 'Pushing boundaries every day', icon2: '🤝', value2: 'Collaboration', desc2: 'Better together', icon3: '⭐', value3: 'Excellence', desc3: 'Delivering our best work' },
  },
  {
    name: 'IT System Status',
    description: 'Dark ops dashboard with status dots, uptime bars, and terminal aesthetic',
    category: 'corporate',
    libraryTags: ['it', 'status', 'monitoring'],
    difficulty: 'advanced',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>${fontsImport}${baseReset}.status{height:100vh;background:#0a0e1a;color:#e2e8f0;padding:3.5vw;display:flex;flex-direction:column;background-image:linear-gradient(rgba(255,255,255,0.02) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,0.02) 1px,transparent 1px);background-size:3vw 3vw}.status h1{font-family:'Inter',sans-serif;font-size:5vw;font-weight:800;margin-bottom:1vh;letter-spacing:-0.02em}.status .subtitle{font-size:2.5vw;color:#64748b;margin-bottom:4vh;font-weight:400}.status .sys{display:flex;justify-content:space-between;align-items:center;padding:2vh 2.5vw;margin-bottom:1.2vh;font-size:2.5vw;background:linear-gradient(135deg,rgba(30,41,59,0.8),rgba(15,23,42,0.6));border-radius:12px;border:1px solid rgba(255,255,255,0.05);box-shadow:0 2px 12px rgba(0,0,0,0.2)}.status .sys-left{display:flex;align-items:center;gap:1.5vw}.status .dot{width:1.4vw;height:1.4vw;border-radius:50%;flex-shrink:0}.status .up{background:#22c55e;box-shadow:0 0 12px rgba(34,197,94,0.5)}.status .down{background:#ef4444;box-shadow:0 0 12px rgba(239,68,68,0.5)}.status .uptime-wrap{display:flex;align-items:center;gap:1.5vw}.status .uptime-bar{width:12vw;height:0.8vh;background:rgba(255,255,255,0.08);border-radius:4px;overflow:hidden}.status .uptime-fill{height:100%;background:linear-gradient(90deg,#22c55e,#4ade80);border-radius:4px}.status .uptime{color:#64748b;font-size:2vw;font-weight:500}</style><div class="status"><h1>System Status</h1><div class="subtitle">All Systems Operational</div><div class="sys"><div class="sys-left"><span class="dot up"></span><span>{{sys1}}</span></div><div class="uptime-wrap"><div class="uptime-bar"><div class="uptime-fill" style="width:99.9%"></div></div><span class="uptime">{{uptime1}}</span></div></div><div class="sys"><div class="sys-left"><span class="dot up"></span><span>{{sys2}}</span></div><div class="uptime-wrap"><div class="uptime-bar"><div class="uptime-fill" style="width:99.5%"></div></div><span class="uptime">{{uptime2}}</span></div></div><div class="sys"><div class="sys-left"><span class="dot up"></span><span>{{sys3}}</span></div><div class="uptime-wrap"><div class="uptime-bar"><div class="uptime-fill" style="width:99.9%"></div></div><span class="uptime">{{uptime3}}</span></div></div><div class="sys"><div class="sys-left"><span class="dot up"></span><span>{{sys4}}</span></div><div class="uptime-wrap"><div class="uptime-bar"><div class="uptime-fill" style="width:99.7%"></div></div><span class="uptime">{{uptime4}}</span></div></div></div>`,
    sampleData: { sys1: 'Email Server', uptime1: '99.99% uptime', sys2: 'VPN Gateway', uptime2: '99.95% uptime', sys3: 'File Storage', uptime3: '99.99% uptime', sys4: 'CRM Platform', uptime4: '99.97% uptime' },
  },
  {
    name: 'Welcome Visitor',
    description: 'Elegant lobby welcome screen with Playfair Display heading and refined branding',
    category: 'corporate',
    libraryTags: ['welcome', 'lobby', 'visitor'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>${fontsImport}${baseReset}.welcome{height:100vh;background:linear-gradient(160deg,#1e1b4b 0%,#4338ca 40%,#6366f1 80%,#818cf8 100%);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;position:relative;overflow:hidden}.welcome::before{content:'';position:absolute;top:50%;left:50%;width:80vw;height:80vw;transform:translate(-50%,-50%);border-radius:50%;background:radial-gradient(circle,rgba(255,255,255,0.04),transparent 60%)}.welcome .inner{position:relative;z-index:1}.welcome .pre{font-size:2.5vw;text-transform:uppercase;letter-spacing:0.2em;opacity:0.7;margin-bottom:2vh;font-weight:500}.welcome h1{font-family:'Playfair Display',serif;font-size:8vw;font-weight:900;margin-bottom:2vh;letter-spacing:-0.02em;text-shadow:0 4px 24px rgba(0,0,0,0.2)}.welcome h2{font-family:'Inter',sans-serif;font-size:3.5vw;font-weight:300;opacity:0.9;margin-bottom:3vh}.welcome .detail{font-size:2.5vw;opacity:0.7;font-weight:400;padding:1.5vh 3vw;border:1px solid rgba(255,255,255,0.2);border-radius:12px;display:inline-block}</style><div class="welcome"><div class="inner"><div class="pre">Welcome</div><h1>{{visitorName}}</h1><h2>{{company}}</h2><div class="detail">{{meetingWith}}</div></div></div>`,
    sampleData: { visitorName: 'John Anderson', company: 'Acme Corp', meetingWith: 'Meeting with Sarah — Room 3B' },
  },
  {
    name: 'Project Timeline',
    description: 'Clean horizontal timeline with connected dots, color-coded phases, and milestone markers',
    category: 'corporate',
    libraryTags: ['project', 'timeline', 'progress'],
    difficulty: 'advanced',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>${fontsImport}${baseReset}.timeline{height:100vh;background:linear-gradient(180deg,#ffffff 0%,#f1f5f9 100%);padding:4vw;display:flex;flex-direction:column;justify-content:center}.timeline h1{font-family:'Playfair Display',serif;font-size:5vw;font-weight:900;color:#0f172a;margin-bottom:6vh;text-align:center;letter-spacing:-0.02em}.timeline .track{display:flex;align-items:flex-start;justify-content:space-between;padding:0 3vw;position:relative}.timeline .track::before{content:'';position:absolute;top:3.2vw;left:8vw;right:8vw;height:4px;background:#e2e8f0;border-radius:2px}.timeline .track::after{content:'';position:absolute;top:3.2vw;left:8vw;width:45%;height:4px;background:linear-gradient(90deg,#22c55e,#3b82f6);border-radius:2px}.timeline .milestone{text-align:center;flex:1;position:relative;z-index:1}.milestone .dot{width:6.4vw;height:6.4vw;border-radius:50%;margin:0 auto 2vh;display:flex;align-items:center;justify-content:center;font-size:2.5vw;font-weight:800;color:#fff;box-shadow:0 4px 16px rgba(0,0,0,0.12)}.milestone.done .dot{background:linear-gradient(135deg,#22c55e,#16a34a)}.milestone.active .dot{background:linear-gradient(135deg,#3b82f6,#2563eb);box-shadow:0 4px 20px rgba(59,130,246,0.4)}.milestone.pending .dot{background:#cbd5e1;color:#94a3b8}.milestone .label{font-size:2.5vw;color:#334155;font-weight:600;margin-bottom:0.8vh}.milestone .date{font-size:2.5vw;color:#94a3b8;font-weight:400}</style><div class="timeline"><h1>{{projectName}}</h1><div class="track"><div class="milestone done"><div class="dot">1</div><div class="label">{{m1}}</div><div class="date">{{d1}}</div></div><div class="milestone done"><div class="dot">2</div><div class="label">{{m2}}</div><div class="date">{{d2}}</div></div><div class="milestone active"><div class="dot">3</div><div class="label">{{m3}}</div><div class="date">{{d3}}</div></div><div class="milestone pending"><div class="dot">4</div><div class="label">{{m4}}</div><div class="date">{{d4}}</div></div></div></div>`,
    sampleData: { projectName: 'Product Launch 2026', m1: 'Planning', d1: 'Jan', m2: 'Development', d2: 'Feb-Mar', m3: 'Testing', d3: 'Apr', m4: 'Launch', d4: 'May' },
  },
  {
    name: 'Office Directory',
    description: 'Light theme office directory with floor sections, blue headers, and room number badges',
    category: 'corporate',
    libraryTags: ['directory', 'office', 'wayfinding'],
    difficulty: 'intermediate',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${fontsImport}${baseReset}.odir{height:100vh;background:linear-gradient(180deg,#f8fafc 0%,#e2e8f0 100%);padding:4vw;display:flex;flex-direction:column}.odir h1{font-family:'Playfair Display',serif;font-size:5vw;font-weight:900;color:#0f172a;text-align:center;margin-bottom:4vh;letter-spacing:-0.02em}.odir .floor{margin-bottom:3vh;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 16px rgba(0,0,0,0.06)}.odir .floor h2{font-family:'Inter',sans-serif;font-size:2.8vw;font-weight:700;color:#fff;background:linear-gradient(135deg,#2563eb,#3b82f6);padding:1.8vh 2.5vw;letter-spacing:0.02em}.odir .dept{font-size:2.5vw;padding:1.8vh 2.5vw;color:#334155;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #f1f5f9}.odir .dept:last-child{border-bottom:none}.odir .dept .room{background:linear-gradient(135deg,#eff6ff,#dbeafe);color:#2563eb;padding:0.6vh 1.5vw;border-radius:8px;font-weight:700;font-size:2.5vw}</style><div class="odir"><h1>{{building}}</h1><div class="floor"><h2>{{floor1}}</h2><div class="dept"><span>{{dept1}}</span><span class="room">{{room1}}</span></div><div class="dept"><span>{{dept2}}</span><span class="room">{{room2}}</span></div></div><div class="floor"><h2>{{floor2}}</h2><div class="dept"><span>{{dept3}}</span><span class="room">{{room3}}</span></div><div class="dept"><span>{{dept4}}</span><span class="room">{{room4}}</span></div></div></div>`,
    sampleData: { building: 'Building A Directory', floor1: 'Floor 1', dept1: 'Engineering', room1: '101-110', dept2: 'Design', room2: '111-115', floor2: 'Floor 2', dept3: 'Marketing', room3: '201-208', dept4: 'Sales', room4: '209-220' },
  },
  {
    name: 'Emergency Procedures',
    description: 'Bold red emergency display with white text, numbered steps very large and clear',
    category: 'corporate',
    libraryTags: ['emergency', 'safety', 'procedures'],
    difficulty: 'beginner',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${fontsImport}${baseReset}.emergency{height:100vh;background:linear-gradient(160deg,#991b1b 0%,#dc2626 50%,#ef4444 100%);color:#fff;padding:5vw;display:flex;flex-direction:column;justify-content:center;position:relative;overflow:hidden}.emergency::before{content:'';position:absolute;top:3vh;left:3vw;right:3vw;bottom:3vh;border:3px solid rgba(255,255,255,0.15);border-radius:20px;pointer-events:none}.emergency h1{font-family:'Inter',sans-serif;font-size:6vw;text-align:center;margin-bottom:5vh;font-weight:900;text-transform:uppercase;letter-spacing:0.08em;text-shadow:0 2px 12px rgba(0,0,0,0.3)}.emergency .step{font-size:2.8vw;padding:2.5vh 3vw;margin-bottom:1.5vh;background:rgba(255,255,255,0.1);border-radius:12px;display:flex;align-items:center;gap:2vw;backdrop-filter:blur(4px)}.emergency .step .num{background:#fff;color:#dc2626;width:5vw;height:5vw;border-radius:50%;display:flex;align-items:center;justify-content:center;font-weight:900;font-size:2.8vw;flex-shrink:0;box-shadow:0 2px 8px rgba(0,0,0,0.15)}.emergency .step .text{font-weight:500;line-height:1.4}.emergency .contact{margin-top:4vh;font-size:2.8vw;text-align:center;padding:2vh 3vw;background:rgba(0,0,0,0.2);border-radius:12px;font-weight:600;letter-spacing:0.02em}</style><div class="emergency"><h1>{{title}}</h1><div class="step"><span class="num">1</span><span class="text">{{step1}}</span></div><div class="step"><span class="num">2</span><span class="text">{{step2}}</span></div><div class="step"><span class="num">3</span><span class="text">{{step3}}</span></div><div class="contact">{{contact}}</div></div>`,
    sampleData: { title: 'Emergency Evacuation', step1: 'Stay calm and stop what you are doing', step2: 'Proceed to the nearest marked exit', step3: 'Gather at the assembly point in the parking lot', contact: 'Emergency: 911 — Security: ext. 5555' },
  },
  {
    name: 'Team Org Chart',
    description: 'Clean org chart with leader card on top and 4 team member cards in a grid below',
    category: 'corporate',
    libraryTags: ['team', 'org-chart', 'structure'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 25,
    templateHtml: `<style>${fontsImport}${baseReset}.org{height:100vh;background:linear-gradient(180deg,#f8fafc 0%,#e2e8f0 100%);padding:3.5vw;display:flex;flex-direction:column;justify-content:center}.org h1{font-family:'Playfair Display',serif;font-size:5vw;font-weight:900;text-align:center;color:#0f172a;margin-bottom:4vh;letter-spacing:-0.02em}.org .lead{text-align:center;margin-bottom:4vh;position:relative}.org .lead::after{content:'';position:absolute;bottom:-2vh;left:50%;transform:translateX(-50%);width:3px;height:3vh;background:linear-gradient(180deg,#3b82f6,#93c5fd)}.org .lead .card{display:inline-block;background:linear-gradient(135deg,#1e40af,#3b82f6);padding:2.5vh 4vw;border-radius:16px;box-shadow:0 8px 32px rgba(59,130,246,0.25)}.org .lead .name{font-size:3vw;color:#fff;font-weight:700;margin-bottom:0.5vh}.org .lead .role{font-size:2.5vw;color:#bfdbfe;font-weight:400}.org .connector{display:flex;justify-content:center;margin-bottom:2vh}.org .connector::before{content:'';width:60vw;height:3px;background:linear-gradient(90deg,#93c5fd,#3b82f6,#93c5fd);border-radius:2px}.org .team{display:grid;grid-template-columns:repeat(4,1fr);gap:2vw}.org .member{background:#fff;border-radius:16px;padding:3vw 2vw;text-align:center;box-shadow:0 4px 16px rgba(0,0,0,0.06);border-top:4px solid #3b82f6;position:relative}.org .member .avatar{width:6vw;height:6vw;border-radius:50%;background:linear-gradient(135deg,#eff6ff,#dbeafe);margin:0 auto 1.5vh;display:flex;align-items:center;justify-content:center;font-size:2.5vw;font-weight:700;color:#3b82f6}.org .member .name{font-size:2.5vw;font-weight:700;color:#0f172a;margin-bottom:0.5vh}.org .member .role{font-size:2.5vw;color:#64748b;font-weight:400}</style><div class="org"><h1>{{teamName}}</h1><div class="lead"><div class="card"><div class="name">{{leadName}}</div><div class="role">{{leadRole}}</div></div></div><div class="connector"></div><div class="team"><div class="member"><div class="avatar">{{m1Init}}</div><div class="name">{{m1Name}}</div><div class="role">{{m1Role}}</div></div><div class="member"><div class="avatar">{{m2Init}}</div><div class="name">{{m2Name}}</div><div class="role">{{m2Role}}</div></div><div class="member"><div class="avatar">{{m3Init}}</div><div class="name">{{m3Name}}</div><div class="role">{{m3Role}}</div></div><div class="member"><div class="avatar">{{m4Init}}</div><div class="name">{{m4Name}}</div><div class="role">{{m4Role}}</div></div></div></div>`,
    sampleData: { teamName: 'Engineering Team', leadName: 'Alex Kim', leadRole: 'VP Engineering', m1Init: 'JL', m1Name: 'Jordan Lee', m1Role: 'Frontend Lead', m2Init: 'SP', m2Name: 'Sam Patel', m2Role: 'Backend Lead', m3Init: 'CW', m3Name: 'Chris Wu', m3Role: 'DevOps Lead', m4Init: 'TC', m4Name: 'Taylor Chen', m4Role: 'QA Lead' },
  },
];

// ============================================================================
// EDUCATION TEMPLATES (8)
// ============================================================================
export const educationTemplates: TemplateSeed[] = [
  {
    name: 'Class Schedule',
    description: 'Clean class schedule with blue accents, alternating row backgrounds, and time blocks',
    category: 'education',
    libraryTags: ['schedule', 'classes', 'timetable'],
    difficulty: 'intermediate',
    templateOrientation: 'portrait',
    duration: 60,
    templateHtml: `<style>${fontsImport}${baseReset}.schedule{height:100vh;background:linear-gradient(180deg,#ffffff 0%,#f1f5f9 100%);padding:3.5vw;display:flex;flex-direction:column}.schedule h1{font-family:'Playfair Display',serif;font-size:5vw;font-weight:900;color:#0f172a;text-align:center;margin-bottom:1.5vh;letter-spacing:-0.02em}.schedule .subtitle{font-size:2.5vw;color:#3b82f6;text-align:center;margin-bottom:4vh;font-weight:600}.schedule .rows{flex:1;display:flex;flex-direction:column;gap:1.2vh}.schedule .row{display:flex;justify-content:space-between;align-items:center;padding:2vh 2.5vw;border-radius:14px;font-size:2.5vw;border-left:5px solid #3b82f6}.schedule .row:nth-child(odd){background:#fff;box-shadow:0 2px 8px rgba(0,0,0,0.04)}.schedule .row:nth-child(even){background:#eff6ff;box-shadow:0 2px 8px rgba(59,130,246,0.06)}.schedule .time{color:#3b82f6;font-weight:700;min-width:14vw}.schedule .class{color:#0f172a;font-weight:600;flex:1;padding:0 2vw}.schedule .room{color:#64748b;font-weight:500;background:#f1f5f9;padding:0.6vh 1.5vw;border-radius:8px;font-size:2.5vw}</style><div class="schedule"><h1>{{title}}</h1><div class="subtitle">Today's Classes</div><div class="rows"><div class="row"><span class="time">{{time1}}</span><span class="class">{{class1}}</span><span class="room">{{room1}}</span></div><div class="row"><span class="time">{{time2}}</span><span class="class">{{class2}}</span><span class="room">{{room2}}</span></div><div class="row"><span class="time">{{time3}}</span><span class="class">{{class3}}</span><span class="room">{{room3}}</span></div><div class="row"><span class="time">{{time4}}</span><span class="class">{{class4}}</span><span class="room">{{room4}}</span></div></div></div>`,
    sampleData: { title: 'Monday Schedule', time1: '8:00 AM', class1: 'Mathematics', room1: 'Room 201', time2: '9:30 AM', class2: 'English Literature', room2: 'Room 105', time3: '11:00 AM', class3: 'Physics Lab', room3: 'Lab 3', time4: '1:00 PM', class4: 'Computer Science', room4: 'Room 302' },
  },
  {
    name: 'Event Announcement',
    description: 'Vibrant blue-to-purple gradient event announcement with date badge and large event name',
    category: 'education',
    libraryTags: ['event', 'school', 'announcement'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${fontsImport}${baseReset}.event{height:100vh;background:linear-gradient(135deg,#1e40af 0%,#6366f1 50%,#a855f7 100%);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;padding:5vw;position:relative;overflow:hidden}.event::before{content:'';position:absolute;top:-15vh;right:-10vw;width:45vw;height:45vw;border-radius:50%;background:radial-gradient(circle,rgba(255,255,255,0.07),transparent 60%)}.event::after{content:'';position:absolute;bottom:-15vh;left:-10vw;width:40vw;height:40vw;border-radius:50%;background:radial-gradient(circle,rgba(255,255,255,0.05),transparent 60%)}.event .inner{position:relative;z-index:1}.event h1{font-family:'Playfair Display',serif;font-size:6vw;font-weight:900;margin-bottom:3vh;letter-spacing:-0.02em;text-shadow:0 4px 20px rgba(0,0,0,0.2)}.event .date{font-size:3vw;margin-bottom:3vh;display:inline-block;padding:1.5vh 4vw;background:rgba(255,255,255,0.15);border-radius:14px;backdrop-filter:blur(8px);font-weight:600;border:1px solid rgba(255,255,255,0.2)}.event p{font-size:2.5vw;opacity:0.9;max-width:60vw;line-height:1.6;font-weight:300;margin:0 auto}</style><div class="event"><div class="inner"><h1>{{eventName}}</h1><div class="date">{{date}}</div><p>{{details}}</p></div></div>`,
    sampleData: { eventName: 'Science Fair 2026', date: 'March 15 — Main Gymnasium', details: 'All students welcome. Projects due by March 10. Prizes awarded in 3 categories.' },
  },
  {
    name: 'Library Hours',
    description: 'Warm bookish brown and cream theme with elegant Playfair Display serif heading',
    category: 'education',
    libraryTags: ['library', 'hours', 'info'],
    difficulty: 'beginner',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${fontsImport}${baseReset}.library{height:100vh;background:linear-gradient(170deg,#fef3c7 0%,#f5e6c8 40%,#e8d5b0 100%);padding:5vw;display:flex;flex-direction:column;justify-content:center;align-items:center;position:relative;overflow:hidden}.library::before{content:'';position:absolute;top:0;left:0;right:0;height:6px;background:linear-gradient(90deg,#92400e,#b45309,#d97706,#b45309,#92400e)}.library::after{content:'';position:absolute;bottom:0;left:0;right:0;height:6px;background:linear-gradient(90deg,#92400e,#b45309,#d97706,#b45309,#92400e)}.library h1{font-family:'Playfair Display',serif;font-size:6vw;font-weight:900;color:#451a03;margin-bottom:4vh;letter-spacing:-0.01em;text-shadow:0 1px 2px rgba(0,0,0,0.08)}.library .hours-block{background:rgba(255,255,255,0.5);border-radius:16px;padding:4vh 5vw;box-shadow:0 4px 20px rgba(0,0,0,0.06);border:1px solid rgba(146,64,14,0.1);margin-bottom:3vh;text-align:center}.library .hours-block .line{font-size:2.8vw;color:#78350f;line-height:2.2;font-weight:500}.library .note{font-size:2.5vw;color:#92400e;text-align:center;font-style:italic;opacity:0.85;padding:2vh 3vw;background:rgba(255,255,255,0.3);border-radius:12px}</style><div class="library"><h1>{{name}}</h1><div class="hours-block"><div class="line">{{weekday}}</div><div class="line">{{weekend}}</div></div><div class="note">{{note}}</div></div>`,
    sampleData: { name: 'School Library', weekday: 'Monday - Friday: 7:30 AM - 6:00 PM', weekend: 'Saturday: 9:00 AM - 2:00 PM', note: 'Study rooms available by reservation' },
  },
  {
    name: 'Achievement Board',
    description: 'Gold and amber gradient achievement display with trophy-style decoration and large student name',
    category: 'education',
    libraryTags: ['achievement', 'honors', 'recognition'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${fontsImport}${baseReset}.achieve{height:100vh;background:linear-gradient(160deg,#78350f 0%,#b45309 30%,#f59e0b 70%,#fbbf24 100%);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;padding:5vw;position:relative;overflow:hidden}.achieve::before{content:'';position:absolute;top:50%;left:50%;width:60vw;height:60vw;transform:translate(-50%,-50%);border-radius:50%;background:radial-gradient(circle,rgba(255,255,255,0.08),transparent 50%)}.achieve .inner{position:relative;z-index:1}.achieve .trophy{font-size:8vw;margin-bottom:2vh;display:block;filter:drop-shadow(0 4px 12px rgba(0,0,0,0.2))}.achieve h1{font-family:'Inter',sans-serif;font-size:5vw;font-weight:800;margin-bottom:3vh;text-transform:uppercase;letter-spacing:0.1em;text-shadow:0 2px 8px rgba(0,0,0,0.2)}.achieve .name{font-family:'Playfair Display',serif;font-size:6vw;font-weight:900;margin-bottom:2vh;letter-spacing:-0.01em;text-shadow:0 4px 16px rgba(0,0,0,0.15)}.achieve .award{font-size:3vw;opacity:0.92;font-weight:500;margin-bottom:1.5vh}.achieve .detail{font-size:2.5vw;opacity:0.8;font-weight:300;padding:1.5vh 3vw;background:rgba(255,255,255,0.12);border-radius:10px;display:inline-block}</style><div class="achieve"><div class="inner"><span class="trophy">🏆</span><h1>{{heading}}</h1><div class="name">{{studentName}}</div><div class="award">{{award}}</div><div class="detail">{{detail}}</div></div></div>`,
    sampleData: { heading: 'Student of the Week', studentName: 'Emma Thompson', award: 'Outstanding Academic Achievement', detail: 'Perfect scores in Mathematics all semester' },
  },
  {
    name: 'Lunch Menu',
    description: 'Fresh green theme cafeteria menu with 2x2 grid of food item cards',
    category: 'education',
    libraryTags: ['lunch', 'cafeteria', 'menu'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>${fontsImport}${baseReset}.lunch{height:100vh;background:linear-gradient(180deg,#f0fdf4 0%,#dcfce7 100%);padding:4vw;display:flex;flex-direction:column;justify-content:center}.lunch h1{font-family:'Playfair Display',serif;font-size:5vw;font-weight:900;color:#14532d;text-align:center;margin-bottom:1.5vh;letter-spacing:-0.02em}.lunch .day{font-size:2.8vw;color:#16a34a;text-align:center;margin-bottom:4vh;font-weight:600;text-transform:uppercase;letter-spacing:0.08em}.lunch .items{display:grid;grid-template-columns:repeat(2,1fr);gap:2.5vw;padding:0 3vw}.lunch .item{background:#fff;border-radius:16px;padding:3.5vw;text-align:center;box-shadow:0 4px 16px rgba(0,0,0,0.05);border-top:4px solid #22c55e;font-size:2.8vw;color:#1e293b;font-weight:600;display:flex;align-items:center;justify-content:center;position:relative}.lunch .item::before{content:'';position:absolute;top:-4px;left:0;right:0;height:4px;background:linear-gradient(90deg,#22c55e,#4ade80);border-radius:16px 16px 0 0}</style><div class="lunch"><h1>{{title}}</h1><div class="day">{{day}}</div><div class="items"><div class="item">{{entree}}</div><div class="item">{{side}}</div><div class="item">{{drink}}</div><div class="item">{{dessert}}</div></div></div>`,
    sampleData: { title: 'Cafeteria Menu', day: 'Wednesday', entree: 'Grilled Chicken Sandwich', side: 'Garden Salad', drink: 'Apple Juice', dessert: 'Fruit Cup' },
  },
  {
    name: 'Exam Schedule',
    description: 'Dark serious navy theme exam schedule with red header, clear date/subject/room table',
    category: 'education',
    libraryTags: ['exam', 'test', 'schedule'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>${fontsImport}${baseReset}.exam{height:100vh;background:linear-gradient(160deg,#0f172a 0%,#1e293b 60%,#334155 100%);color:#e2e8f0;padding:3.5vw;display:flex;flex-direction:column;justify-content:center}.exam h1{font-family:'Inter',sans-serif;font-size:5vw;font-weight:800;text-align:center;margin-bottom:1vh;letter-spacing:-0.02em}.exam .accent{display:block;width:8vw;height:4px;background:linear-gradient(90deg,#ef4444,#f87171);border-radius:2px;margin:0 auto 4vh}.exam table{width:100%;border-collapse:separate;border-spacing:0;font-size:2.5vw;border-radius:16px;overflow:hidden;box-shadow:0 8px 32px rgba(0,0,0,0.3)}.exam th{background:linear-gradient(135deg,#991b1b,#dc2626);padding:2.2vh 2.5vw;text-align:left;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;font-size:2vw;color:#fff}.exam td{padding:2.2vh 2.5vw;border-bottom:1px solid rgba(255,255,255,0.06)}.exam tr:nth-child(even) td{background:rgba(255,255,255,0.03)}.exam tr:nth-child(odd) td{background:rgba(255,255,255,0.01)}.exam td:first-child{font-weight:600;color:#f87171}</style><div class="exam"><h1>{{title}}</h1><span class="accent"></span><table><tr><th>Date</th><th>Subject</th><th>Time</th><th>Room</th></tr><tr><td>{{date1}}</td><td>{{subject1}}</td><td>{{time1}}</td><td>{{room1}}</td></tr><tr><td>{{date2}}</td><td>{{subject2}}</td><td>{{time2}}</td><td>{{room2}}</td></tr><tr><td>{{date3}}</td><td>{{subject3}}</td><td>{{time3}}</td><td>{{room3}}</td></tr></table></div>`,
    sampleData: { title: 'Final Exam Schedule', date1: 'Dec 15', subject1: 'Mathematics', time1: '9:00 AM', room1: 'Hall A', date2: 'Dec 16', subject2: 'English', time2: '9:00 AM', room2: 'Hall B', date3: 'Dec 17', subject3: 'Science', time3: '9:00 AM', room3: 'Lab 1' },
  },
  {
    name: 'Campus Map Legend',
    description: 'Light theme campus directory with color-coded building code badges and clean rows',
    category: 'education',
    libraryTags: ['campus', 'map', 'directory'],
    difficulty: 'intermediate',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${fontsImport}${baseReset}.campus{height:100vh;background:linear-gradient(180deg,#f8fafc 0%,#e2e8f0 100%);padding:4vw;display:flex;flex-direction:column;justify-content:center}.campus h1{font-family:'Playfair Display',serif;font-size:5vw;font-weight:900;color:#0f172a;text-align:center;margin-bottom:1.5vh;letter-spacing:-0.02em}.campus .subtitle{font-size:2.5vw;text-align:center;color:#64748b;margin-bottom:4vh;font-weight:400}.campus .bldg-list{background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.06)}.campus .bldg{display:flex;align-items:center;padding:2.2vh 3vw;border-bottom:1px solid #f1f5f9;font-size:2.5vw}.campus .bldg:last-child{border-bottom:none}.campus .code{min-width:5vw;height:5vw;display:flex;align-items:center;justify-content:center;border-radius:10px;margin-right:2.5vw;font-weight:800;font-size:2.5vw;color:#fff;box-shadow:0 2px 8px rgba(0,0,0,0.1)}.campus .bldg:nth-child(1) .code{background:linear-gradient(135deg,#3b82f6,#2563eb)}.campus .bldg:nth-child(2) .code{background:linear-gradient(135deg,#22c55e,#16a34a)}.campus .bldg:nth-child(3) .code{background:linear-gradient(135deg,#f59e0b,#d97706)}.campus .bldg:nth-child(4) .code{background:linear-gradient(135deg,#ef4444,#dc2626)}.campus .bldg:nth-child(5) .code{background:linear-gradient(135deg,#8b5cf6,#7c3aed)}.campus .name{color:#1e293b;font-weight:500}</style><div class="campus"><h1>Campus Directory</h1><div class="subtitle">Building Guide</div><div class="bldg-list"><div class="bldg"><span class="code">{{code1}}</span><span class="name">{{bldg1}}</span></div><div class="bldg"><span class="code">{{code2}}</span><span class="name">{{bldg2}}</span></div><div class="bldg"><span class="code">{{code3}}</span><span class="name">{{bldg3}}</span></div><div class="bldg"><span class="code">{{code4}}</span><span class="name">{{bldg4}}</span></div><div class="bldg"><span class="code">{{code5}}</span><span class="name">{{bldg5}}</span></div></div></div>`,
    sampleData: { code1: 'A', bldg1: 'Administration Building', code2: 'B', bldg2: 'Science & Engineering', code3: 'C', bldg3: 'Library & Media Center', code4: 'D', bldg4: 'Arts & Humanities', code5: 'E', bldg5: 'Student Center' },
  },
  {
    name: 'Club Recruitment',
    description: 'Vibrant teal gradient club recruitment poster with bold club name and meeting details card',
    category: 'education',
    libraryTags: ['clubs', 'activities', 'recruitment'],
    difficulty: 'beginner',
    templateOrientation: 'portrait',
    duration: 20,
    templateHtml: `<style>${fontsImport}${baseReset}.club{height:100vh;background:linear-gradient(160deg,#042f2e 0%,#0d9488 50%,#2dd4bf 100%);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;padding:5vw;position:relative;overflow:hidden}.club::before{content:'';position:absolute;top:-20vh;left:-15vw;width:60vw;height:60vw;border-radius:50%;background:radial-gradient(circle,rgba(255,255,255,0.06),transparent 60%)}.club::after{content:'';position:absolute;bottom:-15vh;right:-10vw;width:45vw;height:45vw;border-radius:50%;background:radial-gradient(circle,rgba(255,255,255,0.04),transparent 60%)}.club .inner{position:relative;z-index:1}.club .join{font-size:2.5vw;text-transform:uppercase;letter-spacing:0.2em;opacity:0.8;margin-bottom:2vh;font-weight:600}.club h1{font-family:'Playfair Display',serif;font-size:6vw;font-weight:900;margin-bottom:3vh;letter-spacing:-0.01em;text-shadow:0 4px 16px rgba(0,0,0,0.2)}.club .desc{font-size:2.8vw;margin-bottom:4vh;opacity:0.92;line-height:1.6;font-weight:300;max-width:60vw;margin-left:auto;margin-right:auto}.club .details{background:rgba(255,255,255,0.12);padding:2.5vh 4vw;border-radius:16px;backdrop-filter:blur(8px);font-size:2.8vw;font-weight:500;margin-bottom:3vh;border:1px solid rgba(255,255,255,0.15)}.club .cta{font-size:2.5vw;background:#fff;color:#0d9488;padding:1.8vh 4vw;border-radius:12px;display:inline-block;font-weight:700;box-shadow:0 4px 16px rgba(0,0,0,0.15)}</style><div class="club"><div class="inner"><div class="join">Join Us</div><h1>{{clubName}}</h1><div class="desc">{{description}}</div><div class="details">{{meetingTime}}</div><div class="cta">{{cta}}</div></div></div>`,
    sampleData: { clubName: 'Robotics Club', description: 'Build robots, learn programming, compete nationally', meetingTime: 'Every Tuesday — 3:30 PM — Room 204', cta: 'All skill levels welcome!' },
  },
];
