/**
 * Upgraded Healthcare & Events Templates
 * Design System: Google Fonts (Inter + Playfair Display), rich gradients,
 * CSS Grid, box-shadows, pseudo-elements, min 2.5vw body / 5vw headings
 */

import { TemplateSeed } from './template-seeds';

// ============================================================================
// HEALTHCARE TEMPLATES (8) — Upgraded
// ============================================================================
export const healthcareTemplates: TemplateSeed[] = [
  {
    name: 'Wait Time Display',
    description: 'Clean medical white layout with 3 color-coded department wait time cards',
    category: 'healthcare',
    libraryTags: ['wait-time', 'queue', 'patients'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 15,
    isFeatured: true,
    templateHtml: `<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden}.wait{height:100vh;background:#f4f7fa;display:flex;flex-direction:column;position:relative}.wait .header{background:linear-gradient(135deg,#1a73e8,#0d5bbd);padding:3vh 4vw;display:flex;align-items:center;gap:2vw;box-shadow:0 4px 20px rgba(26,115,232,.3)}.wait .header::after{content:'';position:absolute;top:0;right:0;width:30vw;height:12vh;background:linear-gradient(135deg,rgba(255,255,255,.08),transparent);border-radius:0 0 0 50%}.wait .header h1{font-family:'Playfair Display',serif;font-size:5vw;font-weight:900;color:#fff;letter-spacing:-.02em}.wait .header .pulse{width:1.5vw;height:1.5vw;background:#4ade80;border-radius:50%;box-shadow:0 0 12px rgba(74,222,128,.6);animation:pulse 2s infinite}@keyframes pulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.6;transform:scale(.85)}}.wait .cards{flex:1;display:grid;grid-template-columns:repeat(3,1fr);gap:2.5vw;padding:4vh 4vw;align-items:center}.wait .card{background:#fff;border-radius:20px;padding:4vh 2.5vw;text-align:center;box-shadow:0 8px 32px rgba(0,0,0,.06);border-top:5px solid #e0e0e0;transition:transform .3s}.wait .card.green{border-top-color:#22c55e}.wait .card.amber{border-top-color:#f59e0b}.wait .card.red{border-top-color:#ef4444}.wait .card h3{font-size:2.8vw;font-weight:600;color:#475569;margin-bottom:2vh;letter-spacing:.02em}.wait .card .time{font-size:6vw;font-weight:900;line-height:1}.wait .card .time.green{color:#16a34a}.wait .card .time.amber{color:#d97706}.wait .card .time.red{color:#dc2626}.wait .card .unit{font-size:2.5vw;font-weight:500;color:#94a3b8;margin-top:.5vh}</style><div class="wait"><div class="header"><div class="pulse"></div><h1>{{title}}</h1></div><div class="cards"><div class="card green"><h3>{{dept1}}</h3><div class="time green">{{wait1}}</div><div class="unit">estimated</div></div><div class="card amber"><h3>{{dept2}}</h3><div class="time amber">{{wait2}}</div><div class="unit">estimated</div></div><div class="card green"><h3>{{dept3}}</h3><div class="time green">{{wait3}}</div><div class="unit">estimated</div></div></div></div>`,
    sampleData: { title: 'Current Wait Times', dept1: 'General', wait1: '10 min', dept2: 'Urgent Care', wait2: '25 min', dept3: 'Pharmacy', wait3: '5 min' },
  },
  {
    name: 'Health Tips',
    description: 'Fresh green gradient wellness tips with leaf-style decorative accents',
    category: 'healthcare',
    libraryTags: ['health', 'wellness', 'tips'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden}.tips{height:100vh;background:linear-gradient(160deg,#059669,#34d399,#6ee7b7);display:flex;align-items:center;justify-content:center;text-align:center;padding:8vw;position:relative;overflow:hidden}.tips::before{content:'';position:absolute;top:-10vh;right:-5vw;width:40vw;height:40vw;border-radius:50%;background:rgba(255,255,255,.07);pointer-events:none}.tips::after{content:'';position:absolute;bottom:-15vh;left:-8vw;width:50vw;height:50vw;border-radius:50%;background:rgba(255,255,255,.05);pointer-events:none}.tips .leaf{position:absolute;width:12vw;height:12vw;border:3px solid rgba(255,255,255,.12);border-radius:0 50% 0 50%;transform:rotate(45deg)}.tips .leaf1{top:6vh;right:8vw}.tips .leaf2{bottom:8vh;left:6vw;width:8vw;height:8vw}.tips .content{position:relative;z-index:1;max-width:70vw}.tips h2{font-size:2.8vw;font-weight:500;color:rgba(255,255,255,.85);margin-bottom:2vh;text-transform:uppercase;letter-spacing:.15em}.tips h1{font-family:'Playfair Display',serif;font-size:5.5vw;font-weight:900;color:#fff;margin-bottom:3vh;line-height:1.15;text-shadow:0 2px 20px rgba(0,0,0,.1)}.tips p{font-size:2.5vw;color:rgba(255,255,255,.92);line-height:1.7;font-weight:300}</style><div class="tips"><div class="leaf leaf1"></div><div class="leaf leaf2"></div><div class="content"><h2>{{category}}</h2><h1>{{title}}</h1><p>{{tip}}</p></div></div>`,
    sampleData: { category: 'Wellness Tip', title: 'Stay Hydrated', tip: 'Drink at least 8 glasses of water daily. Proper hydration improves energy, focus, and overall health.' },
  },
  {
    name: 'Visitor Policy',
    description: 'Professional dark navy visitor rules with numbered circle indicators',
    category: 'healthcare',
    libraryTags: ['visitor', 'policy', 'rules'],
    difficulty: 'beginner',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden}.visitor{height:100vh;background:linear-gradient(170deg,#0f172a,#1e293b);color:#fff;padding:5vw;display:flex;flex-direction:column;justify-content:center;position:relative;overflow:hidden}.visitor::before{content:'';position:absolute;top:0;left:0;right:0;height:6px;background:linear-gradient(90deg,#3b82f6,#60a5fa,#93c5fd)}.visitor::after{content:'';position:absolute;bottom:-20vh;right:-10vw;width:45vw;height:45vw;border-radius:50%;background:radial-gradient(circle,rgba(59,130,246,.08),transparent);pointer-events:none}.visitor h1{font-family:'Playfair Display',serif;font-size:5.5vw;margin-bottom:1.5vh;text-align:center;color:#f1f5f9;letter-spacing:-.02em}.visitor .divider{width:8vw;height:4px;background:linear-gradient(90deg,#3b82f6,#60a5fa);margin:0 auto 4vh;border-radius:2px}.visitor .rule{display:flex;align-items:flex-start;gap:2vw;padding:2.5vh 0;border-bottom:1px solid rgba(148,163,184,.12);font-size:2.5vw;color:#cbd5e1;line-height:1.5;position:relative;z-index:1}.visitor .num{min-width:4vw;height:4vw;background:linear-gradient(135deg,#3b82f6,#2563eb);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:2vw;font-weight:700;color:#fff;box-shadow:0 4px 15px rgba(59,130,246,.3);flex-shrink:0}</style><div class="visitor"><h1>{{title}}</h1><div class="divider"></div><div class="rule"><div class="num">1</div><span>{{rule1}}</span></div><div class="rule"><div class="num">2</div><span>{{rule2}}</span></div><div class="rule"><div class="num">3</div><span>{{rule3}}</span></div><div class="rule"><div class="num">4</div><span>{{rule4}}</span></div></div>`,
    sampleData: { title: 'Visitor Guidelines', rule1: 'Visiting hours: 10 AM - 8 PM daily', rule2: 'Maximum 2 visitors per patient at a time', rule3: 'Please sanitize hands upon entering and exiting', rule4: 'Children under 12 must be accompanied by an adult' },
  },
  {
    name: 'Department Directory',
    description: 'White and blue medical department directory with floor location badges',
    category: 'healthcare',
    libraryTags: ['directory', 'departments', 'wayfinding'],
    difficulty: 'intermediate',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden}.hdir{height:100vh;background:#f0f5ff;padding:4vw;display:flex;flex-direction:column;position:relative;overflow:hidden}.hdir::before{content:'';position:absolute;top:0;left:0;right:0;height:5px;background:linear-gradient(90deg,#2563eb,#60a5fa,#2563eb)}.hdir .top{text-align:center;margin-bottom:3vh}.hdir h1{font-family:'Playfair Display',serif;font-size:5vw;color:#1e3a5f;letter-spacing:-.02em}.hdir .subtitle{font-size:2.5vw;color:#64748b;font-weight:400;margin-top:.5vh}.hdir .list{flex:1;display:flex;flex-direction:column;justify-content:center;gap:1.5vh}.hdir .dept{display:flex;align-items:center;justify-content:space-between;padding:2vh 2.5vw;background:#fff;border-radius:14px;box-shadow:0 2px 12px rgba(0,0,0,.04);border-left:4px solid #2563eb}.hdir .dept span{font-size:2.5vw;font-weight:500;color:#334155}.hdir .badge{background:linear-gradient(135deg,#2563eb,#3b82f6);color:#fff;padding:.8vh 2vw;border-radius:10px;font-size:2vw;font-weight:700;box-shadow:0 3px 10px rgba(37,99,235,.25);white-space:nowrap}</style><div class="hdir"><div class="top"><h1>{{facility}}</h1><div class="subtitle">Department Directory</div></div><div class="list"><div class="dept"><span>{{dept1}}</span><div class="badge">{{loc1}}</div></div><div class="dept"><span>{{dept2}}</span><div class="badge">{{loc2}}</div></div><div class="dept"><span>{{dept3}}</span><div class="badge">{{loc3}}</div></div><div class="dept"><span>{{dept4}}</span><div class="badge">{{loc4}}</div></div><div class="dept"><span>{{dept5}}</span><div class="badge">{{loc5}}</div></div></div></div>`,
    sampleData: { facility: 'Hospital Directory', dept1: 'Emergency', loc1: 'Ground Floor', dept2: 'Radiology', loc2: 'Floor 1', dept3: 'Cardiology', loc3: 'Floor 2', dept4: 'Pediatrics', loc4: 'Floor 3', dept5: 'Pharmacy', loc5: 'Ground Floor' },
  },
  {
    name: 'Hand Hygiene Reminder',
    description: 'Bold blue hand washing procedure with 5 numbered visual steps',
    category: 'healthcare',
    libraryTags: ['hygiene', 'safety', 'procedure'],
    difficulty: 'beginner',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden}.hygiene{height:100vh;background:linear-gradient(170deg,#1d4ed8,#2563eb,#3b82f6);color:#fff;padding:5vw;display:flex;flex-direction:column;justify-content:center;align-items:center;position:relative;overflow:hidden}.hygiene::before{content:'';position:absolute;top:5vh;right:5vw;width:20vw;height:20vw;border:3px solid rgba(255,255,255,.08);border-radius:50%;pointer-events:none}.hygiene::after{content:'';position:absolute;bottom:5vh;left:3vw;width:15vw;height:15vw;border:3px solid rgba(255,255,255,.06);border-radius:50%;pointer-events:none}.hygiene h1{font-family:'Playfair Display',serif;font-size:5.5vw;font-weight:900;margin-bottom:1vh;text-shadow:0 2px 20px rgba(0,0,0,.15);text-align:center}.hygiene .icon{font-size:5vw;margin-bottom:2vh}.hygiene .steps{width:100%;max-width:75vw;position:relative;z-index:1}.hygiene .step{display:flex;align-items:center;gap:2.5vw;padding:2vh 0;position:relative}.hygiene .step+.step::before{content:'';position:absolute;top:0;left:2.2vw;width:2px;height:0;border-left:2px dashed rgba(255,255,255,.2)}.hygiene .num{min-width:4.5vw;height:4.5vw;background:rgba(255,255,255,.15);border:2px solid rgba(255,255,255,.3);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:2.5vw;font-weight:800;backdrop-filter:blur(4px);flex-shrink:0}.hygiene .text{font-size:2.5vw;font-weight:400;line-height:1.4;color:rgba(255,255,255,.95)}</style><div class="hygiene"><div class="icon">&#128167;</div><h1>{{title}}</h1><div class="steps"><div class="step"><div class="num">1</div><div class="text">{{step1}}</div></div><div class="step"><div class="num">2</div><div class="text">{{step2}}</div></div><div class="step"><div class="num">3</div><div class="text">{{step3}}</div></div><div class="step"><div class="num">4</div><div class="text">{{step4}}</div></div><div class="step"><div class="num">5</div><div class="text">{{step5}}</div></div></div></div>`,
    sampleData: { title: 'Wash Your Hands', step1: 'Wet hands with clean water', step2: 'Apply soap and lather well', step3: 'Scrub for at least 20 seconds', step4: 'Rinse thoroughly', step5: 'Dry with clean towel or air dry' },
  },
  {
    name: 'Flu Season Alert',
    description: 'Warning red seasonal flu alert with shield decoration and prevention tips',
    category: 'healthcare',
    libraryTags: ['flu', 'seasonal', 'prevention'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    seasonalStart: '2026-10-01',
    seasonalEnd: '2027-03-31',
    templateHtml: `<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden}.flu{height:100vh;background:linear-gradient(150deg,#991b1b,#dc2626,#b91c1c);color:#fff;display:flex;align-items:center;justify-content:center;position:relative;overflow:hidden}.flu::before{content:'+';position:absolute;top:8vh;right:8vw;font-size:18vw;font-weight:900;color:rgba(255,255,255,.04);line-height:1;pointer-events:none}.flu .shield{position:absolute;left:5vw;top:50%;transform:translateY(-50%);width:18vw;height:22vw;border:4px solid rgba(255,255,255,.08);border-radius:50% 50% 50% 50%/60% 60% 40% 40%;pointer-events:none}.flu .shield::after{content:'+';position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);font-size:6vw;font-weight:300;color:rgba(255,255,255,.1)}.flu .content{position:relative;z-index:1;text-align:center;max-width:70vw;padding:5vw}.flu h1{font-family:'Playfair Display',serif;font-size:5.5vw;font-weight:900;margin-bottom:4vh;text-shadow:0 3px 20px rgba(0,0,0,.2);line-height:1.15}.flu .tips{display:flex;flex-direction:column;gap:2vh}.flu .tip{display:flex;align-items:center;gap:2vw;font-size:2.5vw;font-weight:400;color:rgba(255,255,255,.92);background:rgba(255,255,255,.08);padding:2vh 3vw;border-radius:12px;backdrop-filter:blur(4px);border:1px solid rgba(255,255,255,.1)}.flu .tip .dot{width:1.2vw;height:1.2vw;background:#fff;border-radius:50%;flex-shrink:0;box-shadow:0 0 8px rgba(255,255,255,.4)}</style><div class="flu"><div class="shield"></div><div class="content"><h1>{{title}}</h1><div class="tips"><div class="tip"><div class="dot"></div><span>{{tip1}}</span></div><div class="tip"><div class="dot"></div><span>{{tip2}}</span></div><div class="tip"><div class="dot"></div><span>{{tip3}}</span></div></div></div></div>`,
    sampleData: { title: 'Flu Season — Protect Yourself', tip1: 'Get your flu vaccination', tip2: 'Wash hands frequently', tip3: 'Stay home if you feel unwell' },
  },
  {
    name: 'Patient Satisfaction',
    description: 'Clean white satisfaction scores with large colored ring indicators',
    category: 'healthcare',
    libraryTags: ['satisfaction', 'scores', 'quality'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 25,
    templateHtml: `<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden}.satisfaction{height:100vh;background:#f8fafc;padding:4vw;display:flex;flex-direction:column;position:relative}.satisfaction::after{content:'';position:absolute;bottom:0;left:0;right:0;height:5px;background:linear-gradient(90deg,#22c55e,#16a34a,#22c55e)}.satisfaction .header{text-align:center;margin-bottom:5vh}.satisfaction h1{font-family:'Playfair Display',serif;font-size:5vw;color:#0f172a;letter-spacing:-.02em}.satisfaction .sub{font-size:2.5vw;color:#64748b;font-weight:300;margin-top:.5vh}.satisfaction .scores{flex:1;display:grid;grid-template-columns:repeat(3,1fr);gap:3vw;align-items:center}.satisfaction .score{text-align:center;display:flex;flex-direction:column;align-items:center}.satisfaction .ring{width:16vw;height:16vw;border-radius:50%;border:6px solid #e2e8f0;position:relative;display:flex;align-items:center;justify-content:center;background:#fff;box-shadow:0 8px 30px rgba(0,0,0,.06)}.satisfaction .ring::before{content:'';position:absolute;inset:-6px;border-radius:50%;border:6px solid transparent;border-top-color:#22c55e;border-right-color:#22c55e;border-bottom-color:#22c55e;animation:none}.satisfaction .ring .val{font-size:4.5vw;font-weight:900;color:#16a34a;line-height:1}.satisfaction .label{font-size:2.5vw;color:#475569;margin-top:2vh;font-weight:500}</style><div class="satisfaction"><div class="header"><h1>{{title}}</h1><div class="sub">Latest quarterly results</div></div><div class="scores"><div class="score"><div class="ring"><div class="val">{{score1}}</div></div><div class="label">{{label1}}</div></div><div class="score"><div class="ring"><div class="val">{{score2}}</div></div><div class="label">{{label2}}</div></div><div class="score"><div class="ring"><div class="val">{{score3}}</div></div><div class="label">{{label3}}</div></div></div></div>`,
    sampleData: { title: 'Patient Satisfaction Scores', score1: '4.8/5', label1: 'Overall Care', score2: '96%', label2: 'Would Recommend', score3: '4.9/5', label3: 'Staff Friendliness' },
  },
  {
    name: 'Vaccination Info',
    description: 'Purple gradient vaccination information with frosted-glass cards',
    category: 'healthcare',
    libraryTags: ['vaccination', 'immunization', 'schedule'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 25,
    templateHtml: `<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden}.vax{height:100vh;background:linear-gradient(160deg,#581c87,#7c3aed,#a78bfa);padding:4vw;display:flex;flex-direction:column;justify-content:center;position:relative;overflow:hidden}.vax::before{content:'';position:absolute;top:-15vh;right:-10vw;width:45vw;height:45vw;border-radius:50%;background:radial-gradient(circle,rgba(255,255,255,.06),transparent);pointer-events:none}.vax::after{content:'';position:absolute;bottom:-10vh;left:-5vw;width:30vw;height:30vw;border-radius:50%;background:radial-gradient(circle,rgba(255,255,255,.04),transparent);pointer-events:none}.vax h1{font-family:'Playfair Display',serif;font-size:5.5vw;color:#fff;text-align:center;margin-bottom:4vh;text-shadow:0 2px 20px rgba(0,0,0,.15);position:relative;z-index:1}.vax .info{display:grid;grid-template-columns:repeat(2,1fr);gap:3vw;position:relative;z-index:1}.vax .card{background:rgba(255,255,255,.12);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);border:1px solid rgba(255,255,255,.18);border-radius:20px;padding:4vh 3vw;text-align:center;box-shadow:0 8px 32px rgba(0,0,0,.1)}.vax .card h3{font-size:3vw;font-weight:700;color:#fff;margin-bottom:2vh}.vax .card p{font-size:2.5vw;color:rgba(255,255,255,.85);line-height:1.6;font-weight:300}</style><div class="vax"><h1>{{title}}</h1><div class="info"><div class="card"><h3>{{vax1}}</h3><p>{{info1}}</p></div><div class="card"><h3>{{vax2}}</h3><p>{{info2}}</p></div></div></div>`,
    sampleData: { title: 'Vaccinations Available', vax1: 'Flu Vaccine', info1: 'Walk-ins welcome — Mon-Fri 8AM-5PM', vax2: 'COVID Booster', info2: 'By appointment — Call (555) 123-4567' },
  },
];

// ============================================================================
// EVENTS TEMPLATES (8) — Upgraded
// ============================================================================
export const eventsTemplates: TemplateSeed[] = [
  {
    name: 'Event Countdown',
    description: 'Dramatic dark gradient countdown with massive glowing number display',
    category: 'events',
    libraryTags: ['countdown', 'upcoming', 'timer'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 15,
    isFeatured: true,
    templateHtml: `<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden}.countdown{height:100vh;background:linear-gradient(160deg,#0a0a1a,#1a1040,#0f0a2e);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;position:relative;overflow:hidden}.countdown::before{content:'';position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);width:45vw;height:45vw;border-radius:50%;background:radial-gradient(circle,rgba(139,92,246,.15),rgba(139,92,246,.03),transparent);pointer-events:none}.countdown::after{content:'';position:absolute;inset:0;background:radial-gradient(ellipse at 30% 20%,rgba(59,130,246,.08),transparent 50%),radial-gradient(ellipse at 70% 80%,rgba(236,72,153,.06),transparent 50%);pointer-events:none}.countdown .wrap{position:relative;z-index:1}.countdown h1{font-family:'Playfair Display',serif;font-size:5vw;font-weight:900;letter-spacing:-.02em;margin-bottom:3vh;text-shadow:0 0 40px rgba(139,92,246,.3)}.countdown .days{font-size:18vw;font-weight:900;line-height:1;background:linear-gradient(180deg,#fff,#c4b5fd);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;filter:drop-shadow(0 0 60px rgba(139,92,246,.4)) drop-shadow(0 0 120px rgba(139,92,246,.2))}.countdown .label{font-size:3vw;font-weight:300;color:rgba(255,255,255,.6);letter-spacing:.3em;text-transform:uppercase;margin-top:1vh}.countdown .date{font-size:2.5vw;color:rgba(255,255,255,.4);margin-top:3vh;font-weight:300}</style><div class="countdown"><div class="wrap"><h1>{{eventName}}</h1><div class="days">{{daysLeft}}</div><div class="label">Days to Go</div><div class="date">{{eventDate}}</div></div></div>`,
    sampleData: { eventName: 'Annual Conference', daysLeft: '14', eventDate: 'March 22, 2026' },
  },
  {
    name: 'Conference Agenda',
    description: 'Dark elegant agenda with time badges and speaker names in navy and maroon',
    category: 'events',
    libraryTags: ['agenda', 'conference', 'schedule'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden}.agenda{height:100vh;background:linear-gradient(170deg,#0f172a,#1e1b3a);color:#fff;padding:3.5vw;display:flex;flex-direction:column;position:relative;overflow:hidden}.agenda::before{content:'';position:absolute;top:0;left:0;bottom:0;width:5px;background:linear-gradient(180deg,#9f1239,#e11d48,#9f1239)}.agenda::after{content:'';position:absolute;top:-20vh;right:-15vw;width:50vw;height:50vw;border-radius:50%;background:radial-gradient(circle,rgba(159,18,57,.06),transparent);pointer-events:none}.agenda h1{font-family:'Playfair Display',serif;font-size:5vw;text-align:center;margin-bottom:3.5vh;color:#f1f5f9;letter-spacing:-.02em}.agenda .sessions{flex:1;display:flex;flex-direction:column;justify-content:center;gap:1.5vh}.agenda .session{display:flex;align-items:center;padding:2vh 2vw;background:rgba(255,255,255,.03);border-radius:14px;border:1px solid rgba(255,255,255,.06);gap:2.5vw}.agenda .time{background:linear-gradient(135deg,#9f1239,#be123c);padding:1.2vh 2vw;border-radius:10px;font-size:2vw;font-weight:700;min-width:11vw;text-align:center;box-shadow:0 4px 15px rgba(159,18,57,.3);flex-shrink:0}.agenda .details{flex:1;display:flex;justify-content:space-between;align-items:center}.agenda .title{font-size:2.5vw;font-weight:600;color:#f1f5f9}.agenda .speaker{font-size:2vw;color:#94a3b8;font-style:italic;font-weight:300}</style><div class="agenda"><h1>{{eventName}}</h1><div class="sessions"><div class="session"><span class="time">{{time1}}</span><div class="details"><span class="title">{{session1}}</span><span class="speaker">{{speaker1}}</span></div></div><div class="session"><span class="time">{{time2}}</span><div class="details"><span class="title">{{session2}}</span><span class="speaker">{{speaker2}}</span></div></div><div class="session"><span class="time">{{time3}}</span><div class="details"><span class="title">{{session3}}</span><span class="speaker">{{speaker3}}</span></div></div><div class="session"><span class="time">{{time4}}</span><div class="details"><span class="title">{{session4}}</span><span class="speaker">{{speaker4}}</span></div></div></div></div>`,
    sampleData: { eventName: 'Tech Summit 2026', time1: '9:00 AM', session1: 'Keynote: Future of AI', speaker1: 'Dr. Smith', time2: '10:30 AM', session2: 'Workshop: Cloud Architecture', speaker2: 'Jane Doe', time3: '1:00 PM', session3: 'Panel: DevOps Best Practices', speaker3: 'Multiple', time4: '3:00 PM', session4: 'Networking Session', speaker4: '' },
  },
  {
    name: 'Speaker Profile',
    description: 'Clean card layout with speaker name, role, bio, and session details',
    category: 'events',
    libraryTags: ['speaker', 'bio', 'profile'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden}.speaker{height:100vh;background:linear-gradient(160deg,#f8fafc,#e2e8f0);display:flex;align-items:center;justify-content:center;padding:5vw;position:relative;overflow:hidden}.speaker::before{content:'';position:absolute;top:-20vh;left:-15vw;width:50vw;height:50vw;border-radius:50%;background:radial-gradient(circle,rgba(99,102,241,.06),transparent);pointer-events:none}.speaker .card{background:#fff;border-radius:24px;padding:5vh 4vw;box-shadow:0 20px 60px rgba(0,0,0,.08);max-width:80vw;width:100%;position:relative;z-index:1;border-top:5px solid #6366f1}.speaker .label{font-size:2.5vw;font-weight:600;color:#6366f1;text-transform:uppercase;letter-spacing:.15em;margin-bottom:1vh}.speaker h1{font-family:'Playfair Display',serif;font-size:5.5vw;color:#0f172a;margin-bottom:1vh;letter-spacing:-.02em}.speaker .title{font-size:2.8vw;color:#64748b;margin-bottom:3vh;font-weight:400}.speaker .bio{font-size:2.5vw;color:#475569;line-height:1.7;font-weight:300;margin-bottom:3vh}.speaker .session{padding:2.5vh 3vw;background:linear-gradient(135deg,#eef2ff,#e0e7ff);border-radius:14px;font-size:2.5vw;color:#4338ca;font-weight:500;border-left:4px solid #6366f1}</style><div class="speaker"><div class="card"><div class="label">{{label}}</div><h1>{{name}}</h1><div class="title">{{jobTitle}}</div><div class="bio">{{bio}}</div><div class="session">{{sessionInfo}}</div></div></div>`,
    sampleData: { label: 'Keynote Speaker', name: 'Dr. Sarah Chen', jobTitle: 'Chief Technology Officer — TechCorp', bio: 'Award-winning researcher with 20+ years in artificial intelligence and machine learning.', sessionInfo: 'Session: "The Future of AI in Enterprise" — 9:00 AM, Main Hall' },
  },
  {
    name: 'Venue Map',
    description: 'Dark theme venue overview with 4 area cards in a 2x2 grid layout',
    category: 'events',
    libraryTags: ['venue', 'map', 'directions'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden}.venue{height:100vh;background:linear-gradient(160deg,#0f172a,#1e293b);color:#fff;padding:4vw;display:flex;flex-direction:column;position:relative;overflow:hidden}.venue::before{content:'';position:absolute;inset:0;background:radial-gradient(ellipse at 80% 20%,rgba(59,130,246,.06),transparent 50%);pointer-events:none}.venue h1{font-family:'Playfair Display',serif;font-size:5vw;text-align:center;margin-bottom:3.5vh;position:relative;z-index:1}.venue .areas{flex:1;display:grid;grid-template-columns:repeat(2,1fr);grid-template-rows:repeat(2,1fr);gap:2vw;position:relative;z-index:1}.venue .area{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:18px;padding:3vh 2.5vw;display:flex;flex-direction:column;justify-content:center;transition:background .3s}.venue .area h3{font-size:2.8vw;font-weight:700;color:#60a5fa;margin-bottom:1.5vh;padding-bottom:1.5vh;border-bottom:2px solid rgba(96,165,250,.2)}.venue .area p{font-size:2.5vw;color:rgba(255,255,255,.7);line-height:1.5;font-weight:300}</style><div class="venue"><h1>{{venueName}}</h1><div class="areas"><div class="area"><h3>{{area1}}</h3><p>{{desc1}}</p></div><div class="area"><h3>{{area2}}</h3><p>{{desc2}}</p></div><div class="area"><h3>{{area3}}</h3><p>{{desc3}}</p></div><div class="area"><h3>{{area4}}</h3><p>{{desc4}}</p></div></div></div>`,
    sampleData: { venueName: 'Convention Center', area1: 'Main Hall', desc1: 'Ground floor — Keynotes & panels', area2: 'Workshop Rooms', desc2: 'Second floor — Rooms 201-210', area3: 'Exhibition Hall', desc3: 'East wing — Vendor booths', area4: 'Dining Area', desc4: 'West wing — Breakfast & lunch' },
  },
  {
    name: 'Sponsor Wall',
    description: 'Clean white sponsor display with gold and silver tier sections',
    category: 'events',
    libraryTags: ['sponsors', 'partners', 'acknowledgment'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden}.sponsors{height:100vh;background:#fafbfc;padding:4vw;display:flex;flex-direction:column;justify-content:center;align-items:center;position:relative;overflow:hidden}.sponsors::before{content:'';position:absolute;top:0;left:0;right:0;height:5px;background:linear-gradient(90deg,#d4a017,#f4d03f,#d4a017)}.sponsors h1{font-family:'Playfair Display',serif;font-size:5vw;color:#0f172a;margin-bottom:5vh;letter-spacing:-.02em}.sponsors .tier{width:100%;max-width:80vw;margin-bottom:4vh;text-align:center}.sponsors .tier-label{font-size:2.5vw;font-weight:700;text-transform:uppercase;letter-spacing:.2em;margin-bottom:2vh;padding-bottom:1vh;display:inline-block}.sponsors .tier-label.gold{color:#b8860b;border-bottom:3px solid #d4a017}.sponsors .tier-label.silver{color:#6b7280;border-bottom:3px solid #9ca3af}.sponsors .names{display:flex;justify-content:center;gap:5vw;flex-wrap:wrap}.sponsors .name{font-size:3.5vw;font-weight:800;color:#1e293b;padding:1.5vh 3vw;background:#fff;border-radius:12px;box-shadow:0 4px 20px rgba(0,0,0,.06)}.sponsors .silver-tier .name{font-size:2.8vw;font-weight:600;color:#475569;box-shadow:0 2px 12px rgba(0,0,0,.04)}</style><div class="sponsors"><h1>Our Sponsors</h1><div class="tier"><div class="tier-label gold">{{tierLabel1}}</div><div class="names"><span class="name">{{sponsor1}}</span><span class="name">{{sponsor2}}</span></div></div><div class="tier silver-tier"><div class="tier-label silver">{{tierLabel2}}</div><div class="names"><span class="name">{{sponsor3}}</span><span class="name">{{sponsor4}}</span><span class="name">{{sponsor5}}</span></div></div></div>`,
    sampleData: { tierLabel1: 'Gold Sponsors', sponsor1: 'TechCorp', sponsor2: 'InnovateCo', tierLabel2: 'Silver Sponsors', sponsor3: 'DataSoft', sponsor4: 'CloudBase', sponsor5: 'NetPro' },
  },
  {
    name: 'Registration Open',
    description: 'Vibrant purple-to-pink gradient with price badge and call-to-action button',
    category: 'events',
    libraryTags: ['registration', 'cta', 'signup'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 15,
    templateHtml: `<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden}.register{height:100vh;background:linear-gradient(135deg,#7c3aed,#c026d3,#ec4899);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;position:relative;overflow:hidden}.register::before{content:'';position:absolute;top:-15vh;left:-10vw;width:40vw;height:40vw;border-radius:50%;background:rgba(255,255,255,.05);pointer-events:none}.register::after{content:'';position:absolute;bottom:-20vh;right:-10vw;width:50vw;height:50vw;border-radius:50%;background:rgba(255,255,255,.04);pointer-events:none}.register .wrap{position:relative;z-index:1}.register h1{font-family:'Playfair Display',serif;font-size:5.5vw;font-weight:900;margin-bottom:2vh;text-shadow:0 3px 20px rgba(0,0,0,.15)}.register .event{font-size:2.8vw;opacity:.9;margin-bottom:3vh;font-weight:300}.register .price{display:inline-block;font-size:3.5vw;font-weight:800;background:rgba(255,255,255,.15);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);border:1px solid rgba(255,255,255,.2);padding:2vh 4vw;border-radius:16px;margin-bottom:3vh;box-shadow:0 8px 30px rgba(0,0,0,.1)}.register .cta{font-size:2.5vw;font-weight:700;background:#fff;color:#7c3aed;padding:2vh 5vw;border-radius:60px;display:inline-block;box-shadow:0 8px 30px rgba(0,0,0,.15);letter-spacing:.02em}</style><div class="register"><div class="wrap"><h1>Registration Open</h1><div class="event">{{eventName}} — {{date}}</div><div class="price">{{price}}</div><br><div class="cta">{{cta}}</div></div></div>`,
    sampleData: { eventName: 'Annual Tech Conference', date: 'April 15-17, 2026', price: 'Early Bird: $199', cta: 'Register at techconf.com' },
  },
  {
    name: 'Live Poll Results',
    description: 'Dark theme horizontal bar chart with gradient fills and percentage labels',
    category: 'events',
    libraryTags: ['poll', 'live', 'interactive'],
    difficulty: 'advanced',
    templateOrientation: 'landscape',
    duration: 15,
    templateHtml: `<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden}.poll{height:100vh;background:linear-gradient(170deg,#0f172a,#1e1b3a);color:#fff;padding:4vw;display:flex;flex-direction:column;justify-content:center;position:relative;overflow:hidden}.poll::before{content:'';position:absolute;inset:0;background:radial-gradient(ellipse at 50% 0%,rgba(139,92,246,.08),transparent 60%);pointer-events:none}.poll h1{font-family:'Playfair Display',serif;font-size:5vw;text-align:center;margin-bottom:5vh;position:relative;z-index:1;letter-spacing:-.02em}.poll .options{max-width:75vw;margin:0 auto;width:100%;position:relative;z-index:1}.poll .option{margin-bottom:3vh}.poll .meta{display:flex;justify-content:space-between;margin-bottom:1.2vh;align-items:baseline}.poll .opt-label{font-size:2.5vw;font-weight:500;color:#e2e8f0}.poll .pct{font-size:2.8vw;font-weight:800;color:#c4b5fd}.poll .bar-bg{background:rgba(255,255,255,.06);border-radius:12px;height:4.5vh;overflow:hidden;border:1px solid rgba(255,255,255,.05)}.poll .bar-fill{height:100%;border-radius:12px;background:linear-gradient(90deg,#7c3aed,#a855f7,#ec4899);box-shadow:0 0 20px rgba(139,92,246,.3);transition:width .5s}</style><div class="poll"><h1>{{question}}</h1><div class="options"><div class="option"><div class="meta"><span class="opt-label">{{opt1}}</span><span class="pct">{{pct1}}</span></div><div class="bar-bg"><div class="bar-fill" style="width:{{pct1}}"></div></div></div><div class="option"><div class="meta"><span class="opt-label">{{opt2}}</span><span class="pct">{{pct2}}</span></div><div class="bar-bg"><div class="bar-fill" style="width:{{pct2}}"></div></div></div><div class="option"><div class="meta"><span class="opt-label">{{opt3}}</span><span class="pct">{{pct3}}</span></div><div class="bar-bg"><div class="bar-fill" style="width:{{pct3}}"></div></div></div></div></div>`,
    sampleData: { question: 'What technology excites you most?', opt1: 'AI / Machine Learning', pct1: '45%', opt2: 'Cloud Computing', pct2: '30%', opt3: 'Blockchain', pct3: '25%' },
  },
  {
    name: 'WiFi Credentials',
    description: 'Dark theme WiFi credentials with large monospace-style network and password',
    category: 'events',
    libraryTags: ['wifi', 'connectivity', 'info'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Playfair+Display:wght@400;700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;overflow:hidden}.wifi{height:100vh;background:linear-gradient(160deg,#111827,#1f2937);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;position:relative;overflow:hidden}.wifi::before{content:'';position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);width:60vw;height:60vw;border-radius:50%;background:radial-gradient(circle,rgba(59,130,246,.05),transparent);pointer-events:none}.wifi .icon{font-size:5vw;margin-bottom:2vh;opacity:.6;position:relative;z-index:1}.wifi h1{font-family:'Playfair Display',serif;font-size:5vw;margin-bottom:5vh;position:relative;z-index:1;letter-spacing:-.02em}.wifi .creds{position:relative;z-index:1;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:20px;padding:4vh 5vw;display:inline-block;backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px)}.wifi .row{display:flex;align-items:center;gap:2vw;margin-bottom:2vh;font-size:2.5vw}.wifi .row:last-child{margin-bottom:0}.wifi .row .key{color:#60a5fa;font-weight:600;min-width:12vw;text-align:right}.wifi .row .val{font-family:'Courier New',monospace;font-size:3.5vw;font-weight:700;color:#f1f5f9;letter-spacing:.1em;background:rgba(96,165,250,.08);padding:1vh 2vw;border-radius:10px;border:1px solid rgba(96,165,250,.15)}.wifi .note{font-size:2.5vw;color:rgba(255,255,255,.4);margin-top:4vh;font-weight:300;position:relative;z-index:1}</style><div class="wifi"><div class="icon">&#128246;</div><h1>{{title}}</h1><div class="creds"><div class="row"><span class="key">Network</span><span class="val">{{network}}</span></div><div class="row"><span class="key">Password</span><span class="val">{{password}}</span></div></div><div class="note">{{note}}</div></div>`,
    sampleData: { title: 'Free WiFi', network: 'EventGuest-2026', password: 'Welcome2026', note: 'Please do not stream video — bandwidth is shared' },
  },
];
