/**
 * Template Library Seed Data
 * 75+ templates across 7 categories
 */

export interface TemplateSeed {
  name: string;
  description: string;
  category: string;
  libraryTags: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  templateOrientation: 'landscape' | 'portrait' | 'both';
  duration: number;
  isFeatured?: boolean;
  seasonalStart?: string;
  seasonalEnd?: string;
  templateHtml: string;
  sampleData?: Record<string, any>;
}

// Shared CSS snippet for all templates
const baseStyles = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; overflow: hidden; }
`;

// ============================================================================
// RETAIL TEMPLATES (15)
// ============================================================================
const retailTemplates: TemplateSeed[] = [
  {
    name: 'Flash Sale Banner',
    description: 'Bold flash sale announcement with countdown styling',
    category: 'retail',
    libraryTags: ['sale', 'promotion', 'urgent'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 15,
    isFeatured: true,
    templateHtml: `<style>${baseStyles}.sale{display:flex;align-items:center;justify-content:center;height:100vh;background:linear-gradient(135deg,#ff4444,#ff6b35);color:#fff;text-align:center}.sale h1{font-size:6vw;font-weight:900;text-transform:uppercase;text-shadow:2px 2px 4px rgba(0,0,0,.3)}.sale .discount{font-size:12vw;font-weight:900;margin:20px 0}.sale .details{font-size:2.5vw;opacity:.9}</style><div class="sale"><div><h1>{{title}}</h1><div class="discount">{{discount}}</div><div class="details">{{details}}</div></div></div>`,
    sampleData: { title: 'Flash Sale', discount: '50% OFF', details: 'Today Only — All Items' },
  },
  {
    name: 'Product Showcase',
    description: 'Clean product display with price and features',
    category: 'retail',
    libraryTags: ['product', 'showcase', 'pricing'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.product{display:grid;grid-template-columns:1fr 1fr;height:100vh;background:#fff}.product .image{background:url('{{imageUrl}}') center/cover no-repeat;background-color:#f0f0f0}.product .info{display:flex;flex-direction:column;justify-content:center;padding:5vw}.product h1{font-size:3.5vw;color:#333;margin-bottom:2vh}.product .price{font-size:5vw;color:#e74c3c;font-weight:700;margin:2vh 0}.product .features{font-size:1.8vw;color:#666;line-height:1.8}</style><div class="product"><div class="image"></div><div class="info"><h1>{{productName}}</h1><div class="price">{{price}}</div><div class="features">{{features}}</div></div></div>`,
    sampleData: { productName: 'Premium Headphones', price: '$199.99', features: 'Noise Cancelling — 30hr Battery — Hi-Res Audio', imageUrl: '' },
  },
  {
    name: 'Store Hours',
    description: 'Display store operating hours',
    category: 'retail',
    libraryTags: ['hours', 'info', 'schedule'],
    difficulty: 'beginner',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${baseStyles}.hours{height:100vh;background:#1a1a2e;color:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:5vw}.hours h1{font-size:4vw;margin-bottom:4vh;color:#e94560}.hours table{font-size:2.2vw;border-collapse:collapse}.hours td{padding:1vh 3vw;border-bottom:1px solid #333}.hours .today{color:#e94560;font-weight:700}</style><div class="hours"><h1>{{storeName}}</h1><table><tr><td>Monday</td><td>{{mon}}</td></tr><tr><td>Tuesday</td><td>{{tue}}</td></tr><tr><td>Wednesday</td><td>{{wed}}</td></tr><tr><td>Thursday</td><td>{{thu}}</td></tr><tr><td>Friday</td><td>{{fri}}</td></tr><tr><td>Saturday</td><td>{{sat}}</td></tr><tr><td>Sunday</td><td>{{sun}}</td></tr></table></div>`,
    sampleData: { storeName: 'Store Hours', mon: '9AM - 9PM', tue: '9AM - 9PM', wed: '9AM - 9PM', thu: '9AM - 9PM', fri: '9AM - 10PM', sat: '10AM - 10PM', sun: '11AM - 7PM' },
  },
  {
    name: 'New Arrivals Grid',
    description: 'Grid layout showcasing new products',
    category: 'retail',
    libraryTags: ['new', 'grid', 'products'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.grid{height:100vh;background:#fafafa;padding:3vw}.grid h1{font-size:3vw;text-align:center;margin-bottom:3vh;color:#333}.grid .items{display:grid;grid-template-columns:repeat(3,1fr);gap:2vw;height:75vh}.grid .item{background:#fff;border-radius:12px;padding:2vw;box-shadow:0 2px 8px rgba(0,0,0,.08);display:flex;flex-direction:column;align-items:center;justify-content:center}.grid .item h3{font-size:1.8vw;margin-top:1vh}.grid .item .price{font-size:2vw;color:#e74c3c;font-weight:700}</style><div class="grid"><h1>{{title}}</h1><div class="items"><div class="item"><h3>{{item1Name}}</h3><div class="price">{{item1Price}}</div></div><div class="item"><h3>{{item2Name}}</h3><div class="price">{{item2Price}}</div></div><div class="item"><h3>{{item3Name}}</h3><div class="price">{{item3Price}}</div></div></div></div>`,
    sampleData: { title: 'New Arrivals', item1Name: 'Smart Watch', item1Price: '$299', item2Name: 'Wireless Earbuds', item2Price: '$149', item3Name: 'Tablet Stand', item3Price: '$49' },
  },
  {
    name: 'Loyalty Program',
    description: 'Promote store loyalty/rewards program',
    category: 'retail',
    libraryTags: ['loyalty', 'rewards', 'membership'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.loyalty{height:100vh;background:linear-gradient(135deg,#667eea,#764ba2);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;padding:5vw}.loyalty h1{font-size:4vw;margin-bottom:2vh}.loyalty .points{font-size:8vw;font-weight:900;margin:2vh 0}.loyalty p{font-size:2vw;opacity:.9}</style><div class="loyalty"><div><h1>{{programName}}</h1><div class="points">{{reward}}</div><p>{{description}}</p></div></div>`,
    sampleData: { programName: 'Rewards Club', reward: '2X Points', description: 'Sign up today and earn double points on every purchase' },
  },
  {
    name: 'Clearance Rack',
    description: 'Clearance and markdown items display',
    category: 'retail',
    libraryTags: ['clearance', 'markdown', 'sale'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 15,
    templateHtml: `<style>${baseStyles}.clearance{height:100vh;background:#fff;display:flex;align-items:center;justify-content:center;text-align:center}.clearance .badge{background:#ff0;padding:2vh 4vw;transform:rotate(-5deg);display:inline-block;margin-bottom:3vh}.clearance .badge span{font-size:3vw;font-weight:900;color:#c0392b}.clearance h1{font-size:5vw;color:#333}.clearance .range{font-size:3vw;color:#e74c3c;font-weight:700;margin-top:2vh}</style><div class="clearance"><div><div class="badge"><span>CLEARANCE</span></div><h1>{{title}}</h1><div class="range">{{priceRange}}</div></div></div>`,
    sampleData: { title: 'Up to 70% Off Select Items', priceRange: 'Starting at $4.99' },
  },
  {
    name: 'Buy One Get One',
    description: 'BOGO promotion template',
    category: 'retail',
    libraryTags: ['bogo', 'promotion', 'deal'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 15,
    isFeatured: true,
    templateHtml: `<style>${baseStyles}.bogo{height:100vh;background:linear-gradient(135deg,#f093fb,#f5576c);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center}.bogo h1{font-size:5vw;font-weight:900;line-height:1.2}.bogo .sub{font-size:2.5vw;margin-top:3vh;opacity:.9}</style><div class="bogo"><div><h1>BUY ONE<br>GET ONE<br>{{offerType}}</h1><div class="sub">{{details}}</div></div></div>`,
    sampleData: { offerType: 'FREE', details: 'On all footwear — This weekend only' },
  },
  {
    name: 'Gift Card Promo',
    description: 'Gift card promotion display',
    category: 'retail',
    libraryTags: ['gift', 'card', 'promotion'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.gift{height:100vh;background:linear-gradient(135deg,#a18cd1,#fbc2eb);display:flex;align-items:center;justify-content:center;text-align:center;color:#333}.gift h1{font-size:4vw}.gift .amount{font-size:6vw;font-weight:900;margin:2vh 0;color:#6c5ce7}.gift p{font-size:2vw}</style><div class="gift"><div><h1>{{title}}</h1><div class="amount">{{bonus}}</div><p>{{details}}</p></div></div>`,
    sampleData: { title: 'Gift Cards Available', bonus: 'Get $10 Bonus', details: 'With every $50 gift card purchase' },
  },
  {
    name: 'Seasonal Sale',
    description: 'Seasonal/holiday sale promotion',
    category: 'retail',
    libraryTags: ['seasonal', 'holiday', 'sale'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 15,
    seasonalStart: '2026-11-01',
    seasonalEnd: '2027-01-05',
    templateHtml: `<style>${baseStyles}.seasonal{height:100vh;background:linear-gradient(135deg,#c0392b,#2c3e50);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center}.seasonal h1{font-size:5vw;font-weight:900}.seasonal .offer{font-size:8vw;font-weight:900;margin:2vh 0}.seasonal p{font-size:2.2vw;opacity:.9}</style><div class="seasonal"><div><h1>{{season}} Sale</h1><div class="offer">{{discount}}</div><p>{{details}}</p></div></div>`,
    sampleData: { season: 'Holiday', discount: '40% OFF', details: 'Everything in store — Limited time' },
  },
  {
    name: 'Price Comparison',
    description: 'Compare original vs sale price',
    category: 'retail',
    libraryTags: ['price', 'comparison', 'value'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 15,
    templateHtml: `<style>${baseStyles}.compare{height:100vh;background:#fff;display:flex;align-items:center;justify-content:center;text-align:center}.compare h2{font-size:3vw;color:#333;margin-bottom:3vh}.compare .prices{display:flex;gap:5vw;align-items:center}.compare .old{font-size:5vw;color:#999;text-decoration:line-through}.compare .arrow{font-size:4vw;color:#333}.compare .new{font-size:7vw;color:#e74c3c;font-weight:900}</style><div class="compare"><div><h2>{{productName}}</h2><div class="prices"><span class="old">{{originalPrice}}</span><span class="arrow">&rarr;</span><span class="new">{{salePrice}}</span></div></div></div>`,
    sampleData: { productName: 'Premium Package', originalPrice: '$199', salePrice: '$99' },
  },
  {
    name: 'Store Directory',
    description: 'Department/aisle directory display',
    category: 'retail',
    libraryTags: ['directory', 'wayfinding', 'departments'],
    difficulty: 'intermediate',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${baseStyles}.directory{height:100vh;background:#2d3436;color:#fff;padding:4vw}.directory h1{font-size:3.5vw;text-align:center;margin-bottom:3vh;color:#74b9ff}.directory .dept{display:flex;justify-content:space-between;padding:1.5vh 2vw;border-bottom:1px solid #444;font-size:2vw}.directory .dept .floor{color:#74b9ff;font-weight:700}</style><div class="directory"><h1>{{storeName}}</h1><div class="dept"><span>{{dept1}}</span><span class="floor">{{floor1}}</span></div><div class="dept"><span>{{dept2}}</span><span class="floor">{{floor2}}</span></div><div class="dept"><span>{{dept3}}</span><span class="floor">{{floor3}}</span></div><div class="dept"><span>{{dept4}}</span><span class="floor">{{floor4}}</span></div><div class="dept"><span>{{dept5}}</span><span class="floor">{{floor5}}</span></div></div>`,
    sampleData: { storeName: 'Store Directory', dept1: 'Electronics', floor1: 'Floor 1', dept2: 'Clothing', floor2: 'Floor 1', dept3: 'Home & Garden', floor3: 'Floor 2', dept4: 'Sports', floor4: 'Floor 2', dept5: 'Food Court', floor5: 'Floor 3' },
  },
  {
    name: 'Customer Testimonial',
    description: 'Display customer reviews and ratings',
    category: 'retail',
    libraryTags: ['reviews', 'testimonial', 'social-proof'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 15,
    templateHtml: `<style>${baseStyles}.testimonial{height:100vh;background:#f8f9fa;display:flex;align-items:center;justify-content:center;text-align:center;padding:8vw}.testimonial .quote{font-size:2.5vw;color:#333;font-style:italic;line-height:1.6;margin-bottom:3vh}.testimonial .author{font-size:2vw;color:#666}.testimonial .stars{font-size:3vw;color:#f1c40f;margin-bottom:2vh}</style><div class="testimonial"><div><div class="stars">{{stars}}</div><div class="quote">"{{quote}}"</div><div class="author">— {{author}}</div></div></div>`,
    sampleData: { stars: '★★★★★', quote: 'Best shopping experience! The staff was incredibly helpful and the quality is outstanding.', author: 'Sarah M.' },
  },
  {
    name: 'Weekly Deals',
    description: 'Weekly special deals carousel-style layout',
    category: 'retail',
    libraryTags: ['weekly', 'deals', 'specials'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.deals{height:100vh;background:#1e272e;color:#fff;padding:3vw}.deals h1{font-size:3vw;text-align:center;margin-bottom:3vh;color:#ffc312}.deals .grid{display:grid;grid-template-columns:repeat(2,1fr);gap:2vw;height:75vh}.deals .deal{background:#2d3436;border-radius:12px;padding:3vw;display:flex;flex-direction:column;justify-content:center;text-align:center}.deals .deal h3{font-size:2vw;margin-bottom:1vh}.deals .deal .price{font-size:3vw;color:#ffc312;font-weight:700}</style><div class="deals"><h1>This Week's Deals</h1><div class="grid"><div class="deal"><h3>{{deal1Name}}</h3><div class="price">{{deal1Price}}</div></div><div class="deal"><h3>{{deal2Name}}</h3><div class="price">{{deal2Price}}</div></div><div class="deal"><h3>{{deal3Name}}</h3><div class="price">{{deal3Price}}</div></div><div class="deal"><h3>{{deal4Name}}</h3><div class="price">{{deal4Price}}</div></div></div></div>`,
    sampleData: { deal1Name: 'Laptop Stand', deal1Price: '$29.99', deal2Name: 'USB Hub', deal2Price: '$19.99', deal3Name: 'Mouse Pad', deal3Price: '$9.99', deal4Name: 'Cable Kit', deal4Price: '$14.99' },
  },
  {
    name: 'Return Policy',
    description: 'Store return and exchange policy display',
    category: 'retail',
    libraryTags: ['policy', 'returns', 'info'],
    difficulty: 'beginner',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${baseStyles}.policy{height:100vh;background:#fff;padding:5vw;display:flex;flex-direction:column;justify-content:center}.policy h1{font-size:3.5vw;color:#2c3e50;margin-bottom:3vh;text-align:center}.policy .rule{padding:2vh 0;border-bottom:1px solid #eee;font-size:2vw;color:#555}.policy .rule strong{color:#2c3e50}</style><div class="policy"><h1>{{title}}</h1><div class="rule"><strong>{{rule1Title}}:</strong> {{rule1Text}}</div><div class="rule"><strong>{{rule2Title}}:</strong> {{rule2Text}}</div><div class="rule"><strong>{{rule3Title}}:</strong> {{rule3Text}}</div></div>`,
    sampleData: { title: 'Return Policy', rule1Title: 'Timeframe', rule1Text: '30 days from purchase', rule2Title: 'Condition', rule2Text: 'Items must be unused with tags', rule3Title: 'Receipt', rule3Text: 'Original receipt required' },
  },
  {
    name: 'Membership Tiers',
    description: 'Display membership levels and benefits',
    category: 'retail',
    libraryTags: ['membership', 'tiers', 'benefits'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 25,
    templateHtml: `<style>${baseStyles}.tiers{height:100vh;background:#0c0c1d;color:#fff;padding:3vw}.tiers h1{font-size:3vw;text-align:center;margin-bottom:3vh}.tiers .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:2vw;height:70vh}.tiers .tier{border-radius:12px;padding:3vw;text-align:center;display:flex;flex-direction:column;justify-content:center}.tiers .silver{background:linear-gradient(135deg,#636e72,#b2bec3)}.tiers .gold{background:linear-gradient(135deg,#f39c12,#fdcb6e)}.tiers .platinum{background:linear-gradient(135deg,#6c5ce7,#a29bfe)}.tiers .tier h2{font-size:2.5vw;margin-bottom:2vh}.tiers .tier p{font-size:1.5vw;line-height:1.6}</style><div class="tiers"><h1>{{title}}</h1><div class="grid"><div class="tier silver"><h2>{{tier1Name}}</h2><p>{{tier1Benefits}}</p></div><div class="tier gold"><h2>{{tier2Name}}</h2><p>{{tier2Benefits}}</p></div><div class="tier platinum"><h2>{{tier3Name}}</h2><p>{{tier3Benefits}}</p></div></div></div>`,
    sampleData: { title: 'Membership Levels', tier1Name: 'Silver', tier1Benefits: '5% discount\nFree shipping over $50', tier2Name: 'Gold', tier2Benefits: '10% discount\nFree shipping\nEarly access', tier3Name: 'Platinum', tier3Benefits: '15% discount\nFree express shipping\nVIP events' },
  },
];

// ============================================================================
// RESTAURANT TEMPLATES (12)
// ============================================================================
const restaurantTemplates: TemplateSeed[] = [
  {
    name: 'Digital Menu Board',
    description: 'Restaurant menu with categories and prices',
    category: 'restaurant',
    libraryTags: ['menu', 'food', 'pricing'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 30,
    isFeatured: true,
    templateHtml: `<style>${baseStyles}.menu{height:100vh;background:#1a1a2e;color:#fff;padding:3vw}.menu h1{font-size:3vw;text-align:center;margin-bottom:2vh;color:#e94560}.menu .cols{display:grid;grid-template-columns:1fr 1fr;gap:3vw}.menu .item{display:flex;justify-content:space-between;padding:1vh 0;border-bottom:1px solid #333;font-size:1.8vw}.menu .item .price{color:#e94560;font-weight:700}.menu h2{font-size:2.2vw;margin:2vh 0 1vh;color:#e94560}</style><div class="menu"><h1>{{restaurantName}}</h1><div class="cols"><div><h2>{{cat1}}</h2><div class="item"><span>{{item1}}</span><span class="price">{{price1}}</span></div><div class="item"><span>{{item2}}</span><span class="price">{{price2}}</span></div><div class="item"><span>{{item3}}</span><span class="price">{{price3}}</span></div></div><div><h2>{{cat2}}</h2><div class="item"><span>{{item4}}</span><span class="price">{{price4}}</span></div><div class="item"><span>{{item5}}</span><span class="price">{{price5}}</span></div><div class="item"><span>{{item6}}</span><span class="price">{{price6}}</span></div></div></div></div>`,
    sampleData: { restaurantName: 'The Kitchen', cat1: 'Mains', item1: 'Grilled Salmon', price1: '$18', item2: 'Ribeye Steak', price2: '$24', item3: 'Chicken Parmesan', price3: '$16', cat2: 'Sides', item4: 'Caesar Salad', price4: '$8', item5: 'Garlic Bread', price5: '$5', item6: 'Soup of the Day', price6: '$7' },
  },
  {
    name: 'Daily Specials',
    description: 'Highlight daily food specials',
    category: 'restaurant',
    libraryTags: ['specials', 'daily', 'featured'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.specials{height:100vh;background:linear-gradient(135deg,#2d3436,#000);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;padding:5vw}.specials h2{font-size:2.5vw;color:#fdcb6e;margin-bottom:1vh}.specials h1{font-size:4vw;margin-bottom:2vh}.specials .price{font-size:5vw;color:#fdcb6e;font-weight:900;margin:2vh 0}.specials .desc{font-size:2vw;opacity:.8}</style><div class="specials"><div><h2>Today's Special</h2><h1>{{dishName}}</h1><div class="price">{{price}}</div><div class="desc">{{description}}</div></div></div>`,
    sampleData: { dishName: 'Pan-Seared Sea Bass', price: '$22', description: 'Served with roasted vegetables and lemon butter sauce' },
  },
  {
    name: 'Happy Hour',
    description: 'Happy hour drinks and timing',
    category: 'restaurant',
    libraryTags: ['happy-hour', 'drinks', 'bar'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.happy{height:100vh;background:linear-gradient(135deg,#6c5ce7,#fd79a8);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center}.happy h1{font-size:5vw;font-weight:900;margin-bottom:2vh}.happy .time{font-size:3vw;margin-bottom:3vh;opacity:.9}.happy .deals{font-size:2.2vw;line-height:2}</style><div class="happy"><div><h1>Happy Hour</h1><div class="time">{{time}}</div><div class="deals">{{deal1}}<br>{{deal2}}<br>{{deal3}}</div></div></div>`,
    sampleData: { time: 'Mon-Fri — 4PM to 7PM', deal1: 'Draft Beer — $4', deal2: 'House Wine — $5', deal3: 'Appetizers — Half Price' },
  },
  {
    name: 'Combo Meal',
    description: 'Combo meal deal promotion',
    category: 'restaurant',
    libraryTags: ['combo', 'deal', 'value'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 15,
    templateHtml: `<style>${baseStyles}.combo{height:100vh;background:#c0392b;color:#fff;display:flex;align-items:center;justify-content:center;text-align:center}.combo h1{font-size:4vw;margin-bottom:2vh}.combo .price{font-size:8vw;font-weight:900}.combo .includes{font-size:2vw;margin-top:3vh;opacity:.9}</style><div class="combo"><div><h1>{{comboName}}</h1><div class="price">{{price}}</div><div class="includes">{{includes}}</div></div></div>`,
    sampleData: { comboName: 'Family Combo', price: '$29.99', includes: 'Burger + Fries + Drink + Dessert — For the whole family' },
  },
  {
    name: 'Nutrition Info',
    description: 'Nutritional information display',
    category: 'restaurant',
    libraryTags: ['nutrition', 'health', 'info'],
    difficulty: 'intermediate',
    templateOrientation: 'portrait',
    duration: 25,
    templateHtml: `<style>${baseStyles}.nutrition{height:100vh;background:#fff;padding:5vw;display:flex;flex-direction:column;justify-content:center}.nutrition h1{font-size:3vw;color:#27ae60;margin-bottom:3vh;text-align:center}.nutrition .row{display:flex;justify-content:space-between;padding:1.5vh 2vw;font-size:2vw;border-bottom:1px solid #eee}.nutrition .row .val{font-weight:700;color:#27ae60}</style><div class="nutrition"><h1>{{dishName}}</h1><div class="row"><span>Calories</span><span class="val">{{calories}}</span></div><div class="row"><span>Protein</span><span class="val">{{protein}}</span></div><div class="row"><span>Carbs</span><span class="val">{{carbs}}</span></div><div class="row"><span>Fat</span><span class="val">{{fat}}</span></div><div class="row"><span>Fiber</span><span class="val">{{fiber}}</span></div></div>`,
    sampleData: { dishName: 'Grilled Chicken Bowl', calories: '520 kcal', protein: '38g', carbs: '45g', fat: '18g', fiber: '6g' },
  },
  {
    name: 'Catering Menu',
    description: 'Catering packages and pricing',
    category: 'restaurant',
    libraryTags: ['catering', 'events', 'packages'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>${baseStyles}.catering{height:100vh;background:#2d3436;color:#fff;padding:3vw}.catering h1{font-size:3vw;text-align:center;margin-bottom:3vh;color:#fdcb6e}.catering .packages{display:grid;grid-template-columns:repeat(3,1fr);gap:2vw}.catering .pkg{background:#3d3d56;border-radius:12px;padding:3vw;text-align:center}.catering .pkg h2{font-size:2vw;color:#fdcb6e;margin-bottom:1vh}.catering .pkg .price{font-size:3vw;font-weight:900;margin:1vh 0}.catering .pkg p{font-size:1.4vw;opacity:.8;line-height:1.6}</style><div class="catering"><h1>Catering Packages</h1><div class="packages"><div class="pkg"><h2>{{pkg1Name}}</h2><div class="price">{{pkg1Price}}</div><p>{{pkg1Details}}</p></div><div class="pkg"><h2>{{pkg2Name}}</h2><div class="price">{{pkg2Price}}</div><p>{{pkg2Details}}</p></div><div class="pkg"><h2>{{pkg3Name}}</h2><div class="price">{{pkg3Price}}</div><p>{{pkg3Details}}</p></div></div></div>`,
    sampleData: { pkg1Name: 'Basic', pkg1Price: '$15/person', pkg1Details: 'Sandwiches, salad, drinks', pkg2Name: 'Premium', pkg2Price: '$25/person', pkg2Details: 'Hot entrees, sides, dessert', pkg3Name: 'Deluxe', pkg3Price: '$40/person', pkg3Details: 'Chef\'s selection, full bar, dessert bar' },
  },
  {
    name: 'Breakfast Menu',
    description: 'Morning breakfast offerings',
    category: 'restaurant',
    libraryTags: ['breakfast', 'morning', 'menu'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 25,
    templateHtml: `<style>${baseStyles}.breakfast{height:100vh;background:linear-gradient(135deg,#ffecd2,#fcb69f);color:#333;padding:4vw}.breakfast h1{font-size:3.5vw;text-align:center;margin-bottom:3vh}.breakfast .items{display:grid;grid-template-columns:1fr 1fr;gap:1.5vw}.breakfast .item{background:rgba(255,255,255,.7);border-radius:8px;padding:2vw;display:flex;justify-content:space-between;font-size:1.8vw}.breakfast .item .price{font-weight:700;color:#e17055}</style><div class="breakfast"><h1>{{title}}</h1><div class="items"><div class="item"><span>{{item1}}</span><span class="price">{{price1}}</span></div><div class="item"><span>{{item2}}</span><span class="price">{{price2}}</span></div><div class="item"><span>{{item3}}</span><span class="price">{{price3}}</span></div><div class="item"><span>{{item4}}</span><span class="price">{{price4}}</span></div></div></div>`,
    sampleData: { title: 'Breakfast — Served Until 11AM', item1: 'Classic Eggs & Toast', price1: '$8', item2: 'Pancake Stack', price2: '$10', item3: 'Avocado Toast', price3: '$12', item4: 'Breakfast Burrito', price4: '$11' },
  },
  {
    name: 'Wine List',
    description: 'Wine selection display',
    category: 'restaurant',
    libraryTags: ['wine', 'drinks', 'bar'],
    difficulty: 'intermediate',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${baseStyles}.wine{height:100vh;background:#1a0a2e;color:#fff;padding:4vw}.wine h1{font-size:3vw;text-align:center;margin-bottom:3vh;color:#d4a574;font-style:italic}.wine .section{margin-bottom:3vh}.wine h2{font-size:2vw;color:#d4a574;margin-bottom:1vh;border-bottom:1px solid #333;padding-bottom:1vh}.wine .item{display:flex;justify-content:space-between;padding:1vh 0;font-size:1.6vw}.wine .item .price{color:#d4a574}</style><div class="wine"><h1>Wine Selection</h1><div class="section"><h2>{{cat1}}</h2><div class="item"><span>{{wine1}}</span><span class="price">{{winePrice1}}</span></div><div class="item"><span>{{wine2}}</span><span class="price">{{winePrice2}}</span></div></div><div class="section"><h2>{{cat2}}</h2><div class="item"><span>{{wine3}}</span><span class="price">{{winePrice3}}</span></div><div class="item"><span>{{wine4}}</span><span class="price">{{winePrice4}}</span></div></div></div>`,
    sampleData: { cat1: 'Red', wine1: 'Cabernet Sauvignon', winePrice1: '$12/glass', wine2: 'Pinot Noir', winePrice2: '$14/glass', cat2: 'White', wine3: 'Chardonnay', winePrice3: '$11/glass', wine4: 'Sauvignon Blanc', winePrice4: '$10/glass' },
  },
  {
    name: 'Food Truck Menu',
    description: 'Compact food truck style menu',
    category: 'restaurant',
    libraryTags: ['food-truck', 'street-food', 'casual'],
    difficulty: 'beginner',
    templateOrientation: 'portrait',
    duration: 25,
    templateHtml: `<style>${baseStyles}.truck{height:100vh;background:#2d3436;color:#fff;padding:4vw;display:flex;flex-direction:column;justify-content:center}.truck h1{font-size:4vw;text-align:center;color:#00b894;margin-bottom:3vh}.truck .item{display:flex;justify-content:space-between;padding:1.5vh 0;border-bottom:1px solid #444;font-size:2vw}.truck .item .price{color:#00b894;font-weight:700}</style><div class="truck"><h1>{{truckName}}</h1><div class="item"><span>{{item1}}</span><span class="price">{{price1}}</span></div><div class="item"><span>{{item2}}</span><span class="price">{{price2}}</span></div><div class="item"><span>{{item3}}</span><span class="price">{{price3}}</span></div><div class="item"><span>{{item4}}</span><span class="price">{{price4}}</span></div></div>`,
    sampleData: { truckName: 'Taco Express', item1: 'Street Tacos (3)', price1: '$9', item2: 'Loaded Nachos', price2: '$11', item3: 'Burrito Bowl', price3: '$12', item4: 'Churros', price4: '$5' },
  },
  {
    name: 'Allergen Notice',
    description: 'Food allergen information display',
    category: 'restaurant',
    libraryTags: ['allergen', 'safety', 'info'],
    difficulty: 'beginner',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${baseStyles}.allergen{height:100vh;background:#fff;padding:5vw;display:flex;flex-direction:column;justify-content:center}.allergen h1{font-size:3vw;color:#e74c3c;text-align:center;margin-bottom:3vh}.allergen .notice{font-size:2vw;text-align:center;color:#555;margin-bottom:3vh;line-height:1.6}.allergen .icons{display:flex;justify-content:center;gap:3vw;flex-wrap:wrap}.allergen .icon{text-align:center;font-size:1.5vw;color:#333}.allergen .icon .symbol{font-size:3vw;margin-bottom:1vh}</style><div class="allergen"><h1>{{title}}</h1><div class="notice">{{notice}}</div><div class="icons"><div class="icon"><div class="symbol">{{icon1}}</div>{{label1}}</div><div class="icon"><div class="symbol">{{icon2}}</div>{{label2}}</div><div class="icon"><div class="symbol">{{icon3}}</div>{{label3}}</div><div class="icon"><div class="symbol">{{icon4}}</div>{{label4}}</div></div></div>`,
    sampleData: { title: 'Allergen Information', notice: 'Please inform our staff of any allergies before ordering', icon1: '🌾', label1: 'Gluten', icon2: '🥜', label2: 'Nuts', icon3: '🥛', label3: 'Dairy', icon4: '🥚', label4: 'Eggs' },
  },
  {
    name: 'Dessert Menu',
    description: 'Sweet treats and dessert display',
    category: 'restaurant',
    libraryTags: ['dessert', 'sweets', 'menu'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.dessert{height:100vh;background:linear-gradient(135deg,#4a1942,#1a1a2e);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;padding:5vw}.dessert h1{font-size:3.5vw;color:#f8a5c2;margin-bottom:3vh}.dessert .items{display:grid;grid-template-columns:repeat(3,1fr);gap:3vw}.dessert .item h3{font-size:2vw;margin-bottom:1vh}.dessert .item .price{font-size:2.5vw;color:#f8a5c2;font-weight:700}</style><div class="dessert"><div><h1>{{title}}</h1><div class="items"><div class="item"><h3>{{item1}}</h3><div class="price">{{price1}}</div></div><div class="item"><h3>{{item2}}</h3><div class="price">{{price2}}</div></div><div class="item"><h3>{{item3}}</h3><div class="price">{{price3}}</div></div></div></div></div>`,
    sampleData: { title: 'Desserts', item1: 'Tiramisu', price1: '$9', item2: 'Cheesecake', price2: '$8', item3: 'Crème Brûlée', price3: '$10' },
  },
  {
    name: 'Order Status Board',
    description: 'Order ready/in-progress status display',
    category: 'restaurant',
    libraryTags: ['orders', 'status', 'queue'],
    difficulty: 'advanced',
    templateOrientation: 'landscape',
    duration: 10,
    templateHtml: `<style>${baseStyles}.orders{height:100vh;background:#0a0a0a;color:#fff;padding:3vw}.orders h1{font-size:3vw;text-align:center;margin-bottom:3vh}.orders .grid{display:grid;grid-template-columns:1fr 1fr;gap:3vw}.orders .col h2{font-size:2.2vw;text-align:center;padding:1vh;border-radius:8px;margin-bottom:2vh}.orders .ready h2{background:#27ae60}.orders .prep h2{background:#f39c12}.orders .num{font-size:3vw;text-align:center;padding:1vh;border-bottom:1px solid #333}</style><div class="orders"><h1>Order Status</h1><div class="grid"><div class="col ready"><h2>Ready</h2><div class="num">{{ready1}}</div><div class="num">{{ready2}}</div></div><div class="col prep"><h2>Preparing</h2><div class="num">{{prep1}}</div><div class="num">{{prep2}}</div></div></div></div>`,
    sampleData: { ready1: '#142', ready2: '#145', prep1: '#147', prep2: '#148' },
  },
];

// ============================================================================
// CORPORATE TEMPLATES (12)
// ============================================================================
const corporateTemplates: TemplateSeed[] = [
  {
    name: 'Company Announcement',
    description: 'Internal company announcements',
    category: 'corporate',
    libraryTags: ['announcement', 'internal', 'news'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    isFeatured: true,
    templateHtml: `<style>${baseStyles}.announce{height:100vh;background:linear-gradient(135deg,#2c3e50,#3498db);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;padding:8vw}.announce h1{font-size:4vw;margin-bottom:3vh}.announce p{font-size:2.2vw;line-height:1.6;opacity:.9}</style><div class="announce"><div><h1>{{title}}</h1><p>{{message}}</p></div></div>`,
    sampleData: { title: 'Company Town Hall', message: 'Join us this Friday at 3 PM in the main conference room for our quarterly update.' },
  },
  {
    name: 'KPI Dashboard',
    description: 'Key performance indicators display',
    category: 'corporate',
    libraryTags: ['kpi', 'metrics', 'dashboard'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 30,
    isFeatured: true,
    templateHtml: `<style>${baseStyles}.kpi{height:100vh;background:#1e272e;color:#fff;padding:3vw}.kpi h1{font-size:2.5vw;text-align:center;margin-bottom:3vh;color:#74b9ff}.kpi .grid{display:grid;grid-template-columns:repeat(4,1fr);gap:2vw}.kpi .card{background:#2d3436;border-radius:12px;padding:3vw;text-align:center}.kpi .card .value{font-size:4vw;font-weight:900;color:#74b9ff;margin-bottom:1vh}.kpi .card .label{font-size:1.4vw;opacity:.7}.kpi .card .change{font-size:1.6vw;margin-top:1vh}</style><div class="kpi"><h1>{{title}}</h1><div class="grid"><div class="card"><div class="value">{{metric1Value}}</div><div class="label">{{metric1Label}}</div><div class="change" style="color:#27ae60">{{metric1Change}}</div></div><div class="card"><div class="value">{{metric2Value}}</div><div class="label">{{metric2Label}}</div><div class="change" style="color:#27ae60">{{metric2Change}}</div></div><div class="card"><div class="value">{{metric3Value}}</div><div class="label">{{metric3Label}}</div><div class="change" style="color:#27ae60">{{metric3Change}}</div></div><div class="card"><div class="value">{{metric4Value}}</div><div class="label">{{metric4Label}}</div><div class="change" style="color:#e74c3c">{{metric4Change}}</div></div></div></div>`,
    sampleData: { title: 'Q1 Performance', metric1Value: '$2.4M', metric1Label: 'Revenue', metric1Change: '+12%', metric2Value: '94%', metric2Label: 'Customer Satisfaction', metric2Change: '+3%', metric3Value: '1,247', metric3Label: 'New Customers', metric3Change: '+18%', metric4Value: '4.2%', metric4Label: 'Churn Rate', metric4Change: '+0.3%' },
  },
  {
    name: 'Meeting Room Schedule',
    description: 'Conference room booking display',
    category: 'corporate',
    libraryTags: ['meeting', 'room', 'schedule'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 60,
    templateHtml: `<style>${baseStyles}.room{height:100vh;background:#fff;padding:3vw}.room h1{font-size:2.5vw;color:#2c3e50;margin-bottom:1vh}.room .status{font-size:1.8vw;margin-bottom:3vh;padding:1vh 2vw;border-radius:8px;display:inline-block}.room .available{background:#27ae60;color:#fff}.room .occupied{background:#e74c3c;color:#fff}.room .schedule{border-collapse:collapse;width:100%;font-size:1.6vw}.room .schedule th{background:#f8f9fa;padding:1.5vh 2vw;text-align:left;color:#555}.room .schedule td{padding:1.5vh 2vw;border-bottom:1px solid #eee}</style><div class="room"><h1>{{roomName}}</h1><div class="status {{statusClass}}">{{statusText}}</div><table class="schedule"><tr><th>Time</th><th>Meeting</th><th>Organizer</th></tr><tr><td>{{time1}}</td><td>{{meeting1}}</td><td>{{org1}}</td></tr><tr><td>{{time2}}</td><td>{{meeting2}}</td><td>{{org2}}</td></tr><tr><td>{{time3}}</td><td>{{meeting3}}</td><td>{{org3}}</td></tr></table></div>`,
    sampleData: { roomName: 'Conference Room A', statusClass: 'available', statusText: 'Available', time1: '9:00 - 10:00', meeting1: 'Sprint Planning', org1: 'J. Smith', time2: '11:00 - 12:00', meeting2: 'Design Review', org2: 'A. Chen', time3: '2:00 - 3:00', meeting3: 'Client Call', org3: 'M. Johnson' },
  },
  {
    name: 'Employee Spotlight',
    description: 'Feature team member achievements',
    category: 'corporate',
    libraryTags: ['employee', 'recognition', 'culture'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.spotlight{height:100vh;background:linear-gradient(135deg,#0c2461,#1e3799);color:#fff;display:flex;align-items:center;justify-content:center;padding:5vw}.spotlight .content{text-align:center}.spotlight h2{font-size:2vw;color:#74b9ff;margin-bottom:1vh}.spotlight h1{font-size:4vw;margin-bottom:2vh}.spotlight .title{font-size:2vw;opacity:.8;margin-bottom:3vh}.spotlight .quote{font-size:2vw;font-style:italic;max-width:60vw;line-height:1.6;opacity:.9}</style><div class="spotlight"><div class="content"><h2>Employee of the Month</h2><h1>{{name}}</h1><div class="title">{{jobTitle}}</div><div class="quote">"{{quote}}"</div></div></div>`,
    sampleData: { name: 'Maria Rodriguez', jobTitle: 'Senior Engineer — Platform Team', quote: 'Exceeded all sprint goals and mentored 3 junior developers this quarter.' },
  },
  {
    name: 'Safety Metrics',
    description: 'Workplace safety statistics',
    category: 'corporate',
    libraryTags: ['safety', 'metrics', 'workplace'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>${baseStyles}.safety{height:100vh;background:#27ae60;color:#fff;display:flex;align-items:center;justify-content:center;text-align:center}.safety h1{font-size:3vw;margin-bottom:3vh}.safety .big{font-size:10vw;font-weight:900;margin:2vh 0}.safety .label{font-size:2.5vw;opacity:.9}.safety .sub{font-size:1.8vw;margin-top:3vh;opacity:.8}</style><div class="safety"><div><h1>{{title}}</h1><div class="big">{{days}}</div><div class="label">{{label}}</div><div class="sub">{{subtext}}</div></div></div>`,
    sampleData: { title: 'Safety First', days: '247', label: 'Days Without Incident', subtext: 'Keep up the great work!' },
  },
  {
    name: 'Company Values',
    description: 'Display core company values',
    category: 'corporate',
    libraryTags: ['values', 'culture', 'mission'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 25,
    templateHtml: `<style>${baseStyles}.values{height:100vh;background:#fff;padding:4vw}.values h1{font-size:3vw;text-align:center;color:#2c3e50;margin-bottom:4vh}.values .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:3vw}.values .value{text-align:center;padding:3vw}.values .value .icon{font-size:4vw;margin-bottom:2vh}.values .value h3{font-size:2vw;color:#2c3e50;margin-bottom:1vh}.values .value p{font-size:1.4vw;color:#666;line-height:1.5}</style><div class="values"><h1>Our Values</h1><div class="grid"><div class="value"><div class="icon">{{icon1}}</div><h3>{{value1}}</h3><p>{{desc1}}</p></div><div class="value"><div class="icon">{{icon2}}</div><h3>{{value2}}</h3><p>{{desc2}}</p></div><div class="value"><div class="icon">{{icon3}}</div><h3>{{value3}}</h3><p>{{desc3}}</p></div></div></div>`,
    sampleData: { icon1: '💡', value1: 'Innovation', desc1: 'Pushing boundaries every day', icon2: '🤝', value2: 'Collaboration', desc2: 'Better together', icon3: '⭐', value3: 'Excellence', desc3: 'Delivering our best work' },
  },
  {
    name: 'IT System Status',
    description: 'System uptime and status board',
    category: 'corporate',
    libraryTags: ['it', 'status', 'monitoring'],
    difficulty: 'advanced',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>${baseStyles}.status{height:100vh;background:#0a0a0a;color:#fff;padding:3vw}.status h1{font-size:2.5vw;margin-bottom:3vh}.status .sys{display:flex;justify-content:space-between;align-items:center;padding:1.5vh 2vw;border-bottom:1px solid #222;font-size:1.8vw}.status .dot{width:1.2vw;height:1.2vw;border-radius:50%;display:inline-block;margin-right:1vw}.status .up{background:#27ae60}.status .down{background:#e74c3c}.status .uptime{color:#888;font-size:1.4vw}</style><div class="status"><h1>System Status</h1><div class="sys"><span><span class="dot up"></span>{{sys1}}</span><span class="uptime">{{uptime1}}</span></div><div class="sys"><span><span class="dot up"></span>{{sys2}}</span><span class="uptime">{{uptime2}}</span></div><div class="sys"><span><span class="dot up"></span>{{sys3}}</span><span class="uptime">{{uptime3}}</span></div><div class="sys"><span><span class="dot up"></span>{{sys4}}</span><span class="uptime">{{uptime4}}</span></div></div>`,
    sampleData: { sys1: 'Email Server', uptime1: '99.99% uptime', sys2: 'VPN Gateway', uptime2: '99.95% uptime', sys3: 'File Storage', uptime3: '99.99% uptime', sys4: 'CRM Platform', uptime4: '99.97% uptime' },
  },
  {
    name: 'Welcome Visitor',
    description: 'Lobby visitor welcome screen',
    category: 'corporate',
    libraryTags: ['welcome', 'lobby', 'visitor'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>${baseStyles}.welcome{height:100vh;background:linear-gradient(135deg,#667eea,#764ba2);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center}.welcome h1{font-size:5vw;margin-bottom:2vh}.welcome h2{font-size:3vw;opacity:.9;margin-bottom:3vh}.welcome p{font-size:2vw;opacity:.8}</style><div class="welcome"><div><h1>Welcome</h1><h2>{{visitorName}}</h2><p>{{company}} — {{meetingWith}}</p></div></div>`,
    sampleData: { visitorName: 'John Anderson', company: 'Acme Corp', meetingWith: 'Meeting with Sarah — Room 3B' },
  },
  {
    name: 'Project Timeline',
    description: 'Project milestones and progress',
    category: 'corporate',
    libraryTags: ['project', 'timeline', 'progress'],
    difficulty: 'advanced',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>${baseStyles}.timeline{height:100vh;background:#fff;padding:3vw}.timeline h1{font-size:2.5vw;color:#2c3e50;margin-bottom:3vh;text-align:center}.timeline .track{display:flex;align-items:center;justify-content:space-between;padding:0 3vw;margin-bottom:3vh}.timeline .milestone{text-align:center;flex:1}.milestone .dot{width:2vw;height:2vw;border-radius:50%;margin:0 auto 1vh;border:3px solid #3498db}.milestone.done .dot{background:#27ae60;border-color:#27ae60}.milestone.active .dot{background:#3498db;border-color:#3498db}.milestone .label{font-size:1.4vw;color:#555}.milestone .date{font-size:1.2vw;color:#999}</style><div class="timeline"><h1>{{projectName}}</h1><div class="track"><div class="milestone done"><div class="dot"></div><div class="label">{{m1}}</div><div class="date">{{d1}}</div></div><div class="milestone done"><div class="dot"></div><div class="label">{{m2}}</div><div class="date">{{d2}}</div></div><div class="milestone active"><div class="dot"></div><div class="label">{{m3}}</div><div class="date">{{d3}}</div></div><div class="milestone"><div class="dot"></div><div class="label">{{m4}}</div><div class="date">{{d4}}</div></div></div></div>`,
    sampleData: { projectName: 'Product Launch 2026', m1: 'Planning', d1: 'Jan', m2: 'Development', d2: 'Feb-Mar', m3: 'Testing', d3: 'Apr', m4: 'Launch', d4: 'May' },
  },
  {
    name: 'Office Directory',
    description: 'Office floor and department directory',
    category: 'corporate',
    libraryTags: ['directory', 'office', 'wayfinding'],
    difficulty: 'intermediate',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${baseStyles}.odir{height:100vh;background:#f8f9fa;padding:4vw}.odir h1{font-size:3vw;color:#2c3e50;text-align:center;margin-bottom:3vh}.odir .floor{margin-bottom:2vh}.odir .floor h2{font-size:2vw;color:#3498db;margin-bottom:1vh;padding-bottom:1vh;border-bottom:2px solid #3498db}.odir .dept{font-size:1.8vw;padding:1vh 0;color:#555;display:flex;justify-content:space-between}.odir .dept .room{color:#3498db}</style><div class="odir"><h1>{{building}}</h1><div class="floor"><h2>{{floor1}}</h2><div class="dept"><span>{{dept1}}</span><span class="room">{{room1}}</span></div><div class="dept"><span>{{dept2}}</span><span class="room">{{room2}}</span></div></div><div class="floor"><h2>{{floor2}}</h2><div class="dept"><span>{{dept3}}</span><span class="room">{{room3}}</span></div><div class="dept"><span>{{dept4}}</span><span class="room">{{room4}}</span></div></div></div>`,
    sampleData: { building: 'Building A Directory', floor1: 'Floor 1', dept1: 'Engineering', room1: '101-110', dept2: 'Design', room2: '111-115', floor2: 'Floor 2', dept3: 'Marketing', room3: '201-208', dept4: 'Sales', room4: '209-220' },
  },
  {
    name: 'Emergency Procedures',
    description: 'Emergency evacuation and contact info',
    category: 'corporate',
    libraryTags: ['emergency', 'safety', 'procedures'],
    difficulty: 'beginner',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${baseStyles}.emergency{height:100vh;background:#e74c3c;color:#fff;padding:5vw;display:flex;flex-direction:column;justify-content:center}.emergency h1{font-size:4vw;text-align:center;margin-bottom:3vh}.emergency .step{font-size:2.2vw;padding:2vh 0;border-bottom:1px solid rgba(255,255,255,.3)}.emergency .step strong{font-size:2.5vw}.emergency .contact{margin-top:3vh;font-size:2vw;text-align:center;opacity:.9}</style><div class="emergency"><h1>{{title}}</h1><div class="step"><strong>1.</strong> {{step1}}</div><div class="step"><strong>2.</strong> {{step2}}</div><div class="step"><strong>3.</strong> {{step3}}</div><div class="contact">{{contact}}</div></div>`,
    sampleData: { title: 'Emergency Evacuation', step1: 'Stay calm and stop what you are doing', step2: 'Proceed to the nearest marked exit', step3: 'Gather at the assembly point in the parking lot', contact: 'Emergency: 911 — Security: ext. 5555' },
  },
  {
    name: 'Team Org Chart',
    description: 'Team structure overview',
    category: 'corporate',
    libraryTags: ['team', 'org-chart', 'structure'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 25,
    templateHtml: `<style>${baseStyles}.org{height:100vh;background:#fff;padding:3vw}.org h1{font-size:2.5vw;text-align:center;color:#2c3e50;margin-bottom:4vh}.org .lead{text-align:center;margin-bottom:3vh}.org .lead .name{font-size:2.5vw;color:#2c3e50;font-weight:700}.org .lead .role{font-size:1.6vw;color:#666}.org .team{display:grid;grid-template-columns:repeat(4,1fr);gap:2vw}.org .member{background:#f8f9fa;border-radius:8px;padding:2vw;text-align:center}.org .member .name{font-size:1.6vw;font-weight:700;color:#2c3e50}.org .member .role{font-size:1.2vw;color:#666}</style><div class="org"><h1>{{teamName}}</h1><div class="lead"><div class="name">{{leadName}}</div><div class="role">{{leadRole}}</div></div><div class="team"><div class="member"><div class="name">{{m1Name}}</div><div class="role">{{m1Role}}</div></div><div class="member"><div class="name">{{m2Name}}</div><div class="role">{{m2Role}}</div></div><div class="member"><div class="name">{{m3Name}}</div><div class="role">{{m3Role}}</div></div><div class="member"><div class="name">{{m4Name}}</div><div class="role">{{m4Role}}</div></div></div></div>`,
    sampleData: { teamName: 'Engineering Team', leadName: 'Alex Kim', leadRole: 'VP Engineering', m1Name: 'Jordan Lee', m1Role: 'Frontend Lead', m2Name: 'Sam Patel', m2Role: 'Backend Lead', m3Name: 'Chris Wu', m3Role: 'DevOps Lead', m4Name: 'Taylor Chen', m4Role: 'QA Lead' },
  },
];

// ============================================================================
// EDUCATION TEMPLATES (8)
// ============================================================================
const educationTemplates: TemplateSeed[] = [
  {
    name: 'Class Schedule',
    description: 'Daily class schedule display',
    category: 'education',
    libraryTags: ['schedule', 'classes', 'timetable'],
    difficulty: 'intermediate',
    templateOrientation: 'portrait',
    duration: 60,
    templateHtml: `<style>${baseStyles}.schedule{height:100vh;background:#fff;padding:3vw}.schedule h1{font-size:3vw;color:#2c3e50;text-align:center;margin-bottom:3vh}.schedule .row{display:flex;justify-content:space-between;padding:1.5vh 2vw;border-bottom:1px solid #eee;font-size:1.8vw;align-items:center}.schedule .time{color:#3498db;font-weight:700;min-width:12vw}.schedule .class{color:#2c3e50}.schedule .room{color:#999}</style><div class="schedule"><h1>{{title}}</h1><div class="row"><span class="time">{{time1}}</span><span class="class">{{class1}}</span><span class="room">{{room1}}</span></div><div class="row"><span class="time">{{time2}}</span><span class="class">{{class2}}</span><span class="room">{{room2}}</span></div><div class="row"><span class="time">{{time3}}</span><span class="class">{{class3}}</span><span class="room">{{room3}}</span></div><div class="row"><span class="time">{{time4}}</span><span class="class">{{class4}}</span><span class="room">{{room4}}</span></div></div>`,
    sampleData: { title: 'Monday Schedule', time1: '8:00 AM', class1: 'Mathematics', room1: 'Room 201', time2: '9:30 AM', class2: 'English Literature', room2: 'Room 105', time3: '11:00 AM', class3: 'Physics Lab', room3: 'Lab 3', time4: '1:00 PM', class4: 'Computer Science', room4: 'Room 302' },
  },
  {
    name: 'Event Announcement',
    description: 'School event promotion',
    category: 'education',
    libraryTags: ['event', 'school', 'announcement'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.event{height:100vh;background:linear-gradient(135deg,#0984e3,#6c5ce7);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;padding:5vw}.event h1{font-size:4vw;margin-bottom:2vh}.event .date{font-size:3vw;margin-bottom:2vh;opacity:.9}.event p{font-size:2vw;opacity:.8;max-width:60vw;line-height:1.5}</style><div class="event"><div><h1>{{eventName}}</h1><div class="date">{{date}}</div><p>{{details}}</p></div></div>`,
    sampleData: { eventName: 'Science Fair 2026', date: 'March 15 — Main Gymnasium', details: 'All students welcome. Projects due by March 10. Prizes awarded in 3 categories.' },
  },
  {
    name: 'Library Hours',
    description: 'Library operating hours and info',
    category: 'education',
    libraryTags: ['library', 'hours', 'info'],
    difficulty: 'beginner',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${baseStyles}.library{height:100vh;background:#f0e6d3;padding:5vw;display:flex;flex-direction:column;justify-content:center;align-items:center}.library h1{font-size:3.5vw;color:#5d4037;margin-bottom:3vh}.library .hours{font-size:2vw;color:#5d4037;line-height:2;text-align:center}.library .note{margin-top:3vh;font-size:1.6vw;color:#8d6e63;text-align:center}</style><div class="library"><h1>{{name}}</h1><div class="hours">{{weekday}}<br>{{weekend}}</div><div class="note">{{note}}</div></div>`,
    sampleData: { name: 'School Library', weekday: 'Monday - Friday: 7:30 AM - 6:00 PM', weekend: 'Saturday: 9:00 AM - 2:00 PM', note: 'Study rooms available by reservation' },
  },
  {
    name: 'Achievement Board',
    description: 'Student achievements and honors',
    category: 'education',
    libraryTags: ['achievement', 'honors', 'recognition'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.achieve{height:100vh;background:linear-gradient(135deg,#fdcb6e,#f39c12);color:#333;display:flex;align-items:center;justify-content:center;text-align:center;padding:5vw}.achieve h1{font-size:3.5vw;margin-bottom:3vh}.achieve .name{font-size:5vw;font-weight:900;margin-bottom:2vh}.achieve .award{font-size:2.5vw;opacity:.8}.achieve .detail{font-size:2vw;margin-top:2vh;opacity:.7}</style><div class="achieve"><div><h1>{{heading}}</h1><div class="name">{{studentName}}</div><div class="award">{{award}}</div><div class="detail">{{detail}}</div></div></div>`,
    sampleData: { heading: 'Student of the Week', studentName: 'Emma Thompson', award: 'Outstanding Academic Achievement', detail: 'Perfect scores in Mathematics all semester' },
  },
  {
    name: 'Lunch Menu',
    description: 'School cafeteria daily menu',
    category: 'education',
    libraryTags: ['lunch', 'cafeteria', 'menu'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>${baseStyles}.lunch{height:100vh;background:#fff;padding:4vw}.lunch h1{font-size:3vw;color:#27ae60;text-align:center;margin-bottom:3vh}.lunch .day{font-size:2vw;color:#27ae60;text-align:center;margin-bottom:3vh}.lunch .items{display:grid;grid-template-columns:repeat(2,1fr);gap:2vw;font-size:1.8vw;color:#555}.lunch .item{background:#f0fff0;border-radius:8px;padding:2vw;text-align:center}</style><div class="lunch"><h1>{{title}}</h1><div class="day">{{day}}</div><div class="items"><div class="item">{{entree}}</div><div class="item">{{side}}</div><div class="item">{{drink}}</div><div class="item">{{dessert}}</div></div></div>`,
    sampleData: { title: 'Cafeteria Menu', day: 'Wednesday', entree: 'Grilled Chicken Sandwich', side: 'Garden Salad', drink: 'Apple Juice', dessert: 'Fruit Cup' },
  },
  {
    name: 'Exam Schedule',
    description: 'Upcoming exam dates and rooms',
    category: 'education',
    libraryTags: ['exam', 'test', 'schedule'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>${baseStyles}.exam{height:100vh;background:#2c3e50;color:#fff;padding:3vw}.exam h1{font-size:3vw;text-align:center;margin-bottom:3vh;color:#e74c3c}.exam table{width:100%;border-collapse:collapse;font-size:1.8vw}.exam th{background:#34495e;padding:1.5vh 2vw;text-align:left}.exam td{padding:1.5vh 2vw;border-bottom:1px solid #34495e}</style><div class="exam"><h1>{{title}}</h1><table><tr><th>Date</th><th>Subject</th><th>Time</th><th>Room</th></tr><tr><td>{{date1}}</td><td>{{subject1}}</td><td>{{time1}}</td><td>{{room1}}</td></tr><tr><td>{{date2}}</td><td>{{subject2}}</td><td>{{time2}}</td><td>{{room2}}</td></tr><tr><td>{{date3}}</td><td>{{subject3}}</td><td>{{time3}}</td><td>{{room3}}</td></tr></table></div>`,
    sampleData: { title: 'Final Exam Schedule', date1: 'Dec 15', subject1: 'Mathematics', time1: '9:00 AM', room1: 'Hall A', date2: 'Dec 16', subject2: 'English', time2: '9:00 AM', room2: 'Hall B', date3: 'Dec 17', subject3: 'Science', time3: '9:00 AM', room3: 'Lab 1' },
  },
  {
    name: 'Campus Map Legend',
    description: 'Campus building directory and map key',
    category: 'education',
    libraryTags: ['campus', 'map', 'directory'],
    difficulty: 'intermediate',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${baseStyles}.campus{height:100vh;background:#f8f9fa;padding:4vw}.campus h1{font-size:3vw;color:#2c3e50;text-align:center;margin-bottom:3vh}.campus .bldg{display:flex;align-items:center;padding:1.5vh 2vw;border-bottom:1px solid #ddd;font-size:1.8vw}.campus .code{background:#3498db;color:#fff;padding:.5vh 1vw;border-radius:4px;margin-right:2vw;font-weight:700;min-width:4vw;text-align:center}.campus .name{color:#333}</style><div class="campus"><h1>Campus Directory</h1><div class="bldg"><span class="code">{{code1}}</span><span class="name">{{bldg1}}</span></div><div class="bldg"><span class="code">{{code2}}</span><span class="name">{{bldg2}}</span></div><div class="bldg"><span class="code">{{code3}}</span><span class="name">{{bldg3}}</span></div><div class="bldg"><span class="code">{{code4}}</span><span class="name">{{bldg4}}</span></div><div class="bldg"><span class="code">{{code5}}</span><span class="name">{{bldg5}}</span></div></div>`,
    sampleData: { code1: 'A', bldg1: 'Administration Building', code2: 'B', bldg2: 'Science & Engineering', code3: 'C', bldg3: 'Library & Media Center', code4: 'D', bldg4: 'Arts & Humanities', code5: 'E', bldg5: 'Student Center' },
  },
  {
    name: 'Club Recruitment',
    description: 'Student club/activity recruitment poster',
    category: 'education',
    libraryTags: ['clubs', 'activities', 'recruitment'],
    difficulty: 'beginner',
    templateOrientation: 'portrait',
    duration: 20,
    templateHtml: `<style>${baseStyles}.club{height:100vh;background:linear-gradient(135deg,#00b894,#00cec9);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;padding:5vw}.club h1{font-size:4vw;margin-bottom:2vh}.club .desc{font-size:2vw;margin-bottom:3vh;opacity:.9;line-height:1.5}.club .when{font-size:2.5vw;margin-bottom:2vh}.club .cta{font-size:2vw;background:rgba(255,255,255,.2);padding:1.5vh 3vw;border-radius:8px;display:inline-block}</style><div class="club"><div><h1>{{clubName}}</h1><div class="desc">{{description}}</div><div class="when">{{meetingTime}}</div><div class="cta">{{cta}}</div></div></div>`,
    sampleData: { clubName: 'Robotics Club', description: 'Build robots, learn programming, compete nationally', meetingTime: 'Every Tuesday — 3:30 PM — Room 204', cta: 'All skill levels welcome!' },
  },
];

// ============================================================================
// HEALTHCARE TEMPLATES (8)
// ============================================================================
const healthcareTemplates: TemplateSeed[] = [
  {
    name: 'Wait Time Display',
    description: 'Current estimated wait times',
    category: 'healthcare',
    libraryTags: ['wait-time', 'queue', 'patients'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 15,
    isFeatured: true,
    templateHtml: `<style>${baseStyles}.wait{height:100vh;background:#fff;padding:3vw}.wait h1{font-size:3vw;color:#2c3e50;text-align:center;margin-bottom:3vh}.wait .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:2vw}.wait .dept{background:#f8f9fa;border-radius:12px;padding:3vw;text-align:center}.wait .dept h3{font-size:1.8vw;color:#555;margin-bottom:1vh}.wait .dept .time{font-size:4vw;font-weight:900}.wait .short{color:#27ae60}.wait .medium{color:#f39c12}.wait .long{color:#e74c3c}</style><div class="wait"><h1>{{title}}</h1><div class="grid"><div class="dept"><h3>{{dept1}}</h3><div class="time short">{{wait1}}</div></div><div class="dept"><h3>{{dept2}}</h3><div class="time medium">{{wait2}}</div></div><div class="dept"><h3>{{dept3}}</h3><div class="time short">{{wait3}}</div></div></div></div>`,
    sampleData: { title: 'Current Wait Times', dept1: 'General', wait1: '10 min', dept2: 'Urgent Care', wait2: '25 min', dept3: 'Pharmacy', wait3: '5 min' },
  },
  {
    name: 'Health Tips',
    description: 'Rotating health and wellness tips',
    category: 'healthcare',
    libraryTags: ['health', 'wellness', 'tips'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.tips{height:100vh;background:linear-gradient(135deg,#00b894,#55efc4);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;padding:8vw}.tips h2{font-size:2vw;opacity:.9;margin-bottom:2vh}.tips h1{font-size:3.5vw;margin-bottom:3vh}.tips p{font-size:2vw;line-height:1.6;opacity:.9}</style><div class="tips"><div><h2>{{category}}</h2><h1>{{title}}</h1><p>{{tip}}</p></div></div>`,
    sampleData: { category: 'Wellness Tip', title: 'Stay Hydrated', tip: 'Drink at least 8 glasses of water daily. Proper hydration improves energy, focus, and overall health.' },
  },
  {
    name: 'Visitor Policy',
    description: 'Hospital visitor rules and hours',
    category: 'healthcare',
    libraryTags: ['visitor', 'policy', 'rules'],
    difficulty: 'beginner',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${baseStyles}.visitor{height:100vh;background:#2c3e50;color:#fff;padding:5vw;display:flex;flex-direction:column;justify-content:center}.visitor h1{font-size:3.5vw;margin-bottom:3vh;text-align:center;color:#74b9ff}.visitor .rule{font-size:2vw;padding:2vh 0;border-bottom:1px solid #34495e;line-height:1.5}</style><div class="visitor"><h1>{{title}}</h1><div class="rule">{{rule1}}</div><div class="rule">{{rule2}}</div><div class="rule">{{rule3}}</div><div class="rule">{{rule4}}</div></div>`,
    sampleData: { title: 'Visitor Guidelines', rule1: 'Visiting hours: 10 AM - 8 PM daily', rule2: 'Maximum 2 visitors per patient at a time', rule3: 'Please sanitize hands upon entering and exiting', rule4: 'Children under 12 must be accompanied by an adult' },
  },
  {
    name: 'Department Directory',
    description: 'Hospital department locations',
    category: 'healthcare',
    libraryTags: ['directory', 'departments', 'wayfinding'],
    difficulty: 'intermediate',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${baseStyles}.hdir{height:100vh;background:#fff;padding:4vw}.hdir h1{font-size:3vw;color:#0984e3;text-align:center;margin-bottom:3vh}.hdir .dept{display:flex;justify-content:space-between;padding:1.5vh 2vw;border-bottom:1px solid #eee;font-size:1.8vw}.hdir .dept .loc{color:#0984e3;font-weight:700}</style><div class="hdir"><h1>{{facility}}</h1><div class="dept"><span>{{dept1}}</span><span class="loc">{{loc1}}</span></div><div class="dept"><span>{{dept2}}</span><span class="loc">{{loc2}}</span></div><div class="dept"><span>{{dept3}}</span><span class="loc">{{loc3}}</span></div><div class="dept"><span>{{dept4}}</span><span class="loc">{{loc4}}</span></div><div class="dept"><span>{{dept5}}</span><span class="loc">{{loc5}}</span></div></div>`,
    sampleData: { facility: 'Hospital Directory', dept1: 'Emergency', loc1: 'Ground Floor', dept2: 'Radiology', loc2: 'Floor 1', dept3: 'Cardiology', loc3: 'Floor 2', dept4: 'Pediatrics', loc4: 'Floor 3', dept5: 'Pharmacy', loc5: 'Ground Floor' },
  },
  {
    name: 'Hand Hygiene Reminder',
    description: 'Hand washing procedure display',
    category: 'healthcare',
    libraryTags: ['hygiene', 'safety', 'procedure'],
    difficulty: 'beginner',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${baseStyles}.hygiene{height:100vh;background:#0984e3;color:#fff;padding:5vw;display:flex;flex-direction:column;justify-content:center;text-align:center}.hygiene h1{font-size:3.5vw;margin-bottom:3vh}.hygiene .steps{text-align:left;font-size:2vw;line-height:2.2}.hygiene .steps strong{color:#74b9ff}</style><div class="hygiene"><h1>{{title}}</h1><div class="steps"><strong>1.</strong> {{step1}}<br><strong>2.</strong> {{step2}}<br><strong>3.</strong> {{step3}}<br><strong>4.</strong> {{step4}}<br><strong>5.</strong> {{step5}}</div></div>`,
    sampleData: { title: 'Wash Your Hands', step1: 'Wet hands with clean water', step2: 'Apply soap and lather well', step3: 'Scrub for at least 20 seconds', step4: 'Rinse thoroughly', step5: 'Dry with clean towel or air dry' },
  },
  {
    name: 'Flu Season Alert',
    description: 'Seasonal flu prevention information',
    category: 'healthcare',
    libraryTags: ['flu', 'seasonal', 'prevention'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    seasonalStart: '2026-10-01',
    seasonalEnd: '2027-03-31',
    templateHtml: `<style>${baseStyles}.flu{height:100vh;background:linear-gradient(135deg,#e74c3c,#c0392b);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;padding:5vw}.flu h1{font-size:4vw;margin-bottom:3vh}.flu .tips{font-size:2.2vw;line-height:2;opacity:.9}</style><div class="flu"><div><h1>{{title}}</h1><div class="tips">{{tip1}}<br>{{tip2}}<br>{{tip3}}</div></div></div>`,
    sampleData: { title: 'Flu Season — Protect Yourself', tip1: 'Get your flu vaccination', tip2: 'Wash hands frequently', tip3: 'Stay home if you feel unwell' },
  },
  {
    name: 'Patient Satisfaction',
    description: 'Patient satisfaction scores display',
    category: 'healthcare',
    libraryTags: ['satisfaction', 'scores', 'quality'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 25,
    templateHtml: `<style>${baseStyles}.satisfaction{height:100vh;background:#fff;padding:4vw}.satisfaction h1{font-size:3vw;color:#2c3e50;text-align:center;margin-bottom:4vh}.satisfaction .scores{display:grid;grid-template-columns:repeat(3,1fr);gap:3vw}.satisfaction .score{text-align:center}.satisfaction .score .val{font-size:5vw;font-weight:900;color:#27ae60}.satisfaction .score .label{font-size:1.6vw;color:#666;margin-top:1vh}</style><div class="satisfaction"><h1>{{title}}</h1><div class="scores"><div class="score"><div class="val">{{score1}}</div><div class="label">{{label1}}</div></div><div class="score"><div class="val">{{score2}}</div><div class="label">{{label2}}</div></div><div class="score"><div class="val">{{score3}}</div><div class="label">{{label3}}</div></div></div></div>`,
    sampleData: { title: 'Patient Satisfaction Scores', score1: '4.8/5', label1: 'Overall Care', score2: '96%', label2: 'Would Recommend', score3: '4.9/5', label3: 'Staff Friendliness' },
  },
  {
    name: 'Vaccination Info',
    description: 'Available vaccinations and schedules',
    category: 'healthcare',
    libraryTags: ['vaccination', 'immunization', 'schedule'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 25,
    templateHtml: `<style>${baseStyles}.vax{height:100vh;background:linear-gradient(135deg,#6c5ce7,#a29bfe);color:#fff;padding:4vw}.vax h1{font-size:3vw;text-align:center;margin-bottom:3vh}.vax .info{display:grid;grid-template-columns:repeat(2,1fr);gap:2vw}.vax .card{background:rgba(255,255,255,.15);border-radius:12px;padding:3vw;text-align:center}.vax .card h3{font-size:2vw;margin-bottom:1vh}.vax .card p{font-size:1.5vw;opacity:.9}</style><div class="vax"><h1>{{title}}</h1><div class="info"><div class="card"><h3>{{vax1}}</h3><p>{{info1}}</p></div><div class="card"><h3>{{vax2}}</h3><p>{{info2}}</p></div></div></div>`,
    sampleData: { title: 'Vaccinations Available', vax1: 'Flu Vaccine', info1: 'Walk-ins welcome — Mon-Fri 8AM-5PM', vax2: 'COVID Booster', info2: 'By appointment — Call (555) 123-4567' },
  },
];

// ============================================================================
// EVENTS TEMPLATES (8)
// ============================================================================
const eventsTemplates: TemplateSeed[] = [
  {
    name: 'Event Countdown',
    description: 'Countdown to a major event',
    category: 'events',
    libraryTags: ['countdown', 'upcoming', 'timer'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 15,
    isFeatured: true,
    templateHtml: `<style>${baseStyles}.countdown{height:100vh;background:linear-gradient(135deg,#e74c3c,#c0392b);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center}.countdown h1{font-size:4vw;margin-bottom:3vh}.countdown .days{font-size:12vw;font-weight:900}.countdown .label{font-size:2.5vw;opacity:.9;margin-top:1vh}.countdown .date{font-size:2vw;opacity:.7;margin-top:2vh}</style><div class="countdown"><div><h1>{{eventName}}</h1><div class="days">{{daysLeft}}</div><div class="label">Days to Go</div><div class="date">{{eventDate}}</div></div></div>`,
    sampleData: { eventName: 'Annual Conference', daysLeft: '14', eventDate: 'March 22, 2026' },
  },
  {
    name: 'Conference Agenda',
    description: 'Event schedule/agenda display',
    category: 'events',
    libraryTags: ['agenda', 'conference', 'schedule'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>${baseStyles}.agenda{height:100vh;background:#1a1a2e;color:#fff;padding:3vw}.agenda h1{font-size:3vw;text-align:center;margin-bottom:3vh;color:#e94560}.agenda .session{display:flex;padding:1.5vh 2vw;border-bottom:1px solid #333;font-size:1.8vw;align-items:center}.agenda .time{color:#e94560;font-weight:700;min-width:12vw}.agenda .title{flex:1}.agenda .speaker{color:#888;font-style:italic}</style><div class="agenda"><h1>{{eventName}}</h1><div class="session"><span class="time">{{time1}}</span><span class="title">{{session1}}</span><span class="speaker">{{speaker1}}</span></div><div class="session"><span class="time">{{time2}}</span><span class="title">{{session2}}</span><span class="speaker">{{speaker2}}</span></div><div class="session"><span class="time">{{time3}}</span><span class="title">{{session3}}</span><span class="speaker">{{speaker3}}</span></div><div class="session"><span class="time">{{time4}}</span><span class="title">{{session4}}</span><span class="speaker">{{speaker4}}</span></div></div>`,
    sampleData: { eventName: 'Tech Summit 2026', time1: '9:00 AM', session1: 'Keynote: Future of AI', speaker1: 'Dr. Smith', time2: '10:30 AM', session2: 'Workshop: Cloud Architecture', speaker2: 'Jane Doe', time3: '1:00 PM', session3: 'Panel: DevOps Best Practices', speaker3: 'Multiple', time4: '3:00 PM', session4: 'Networking Session', speaker4: '' },
  },
  {
    name: 'Speaker Profile',
    description: 'Event speaker bio and session info',
    category: 'events',
    libraryTags: ['speaker', 'bio', 'profile'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.speaker{height:100vh;background:#fff;display:flex;align-items:center;padding:5vw}.speaker .info{flex:1}.speaker h2{font-size:2vw;color:#e74c3c;margin-bottom:1vh}.speaker h1{font-size:3.5vw;color:#2c3e50;margin-bottom:1vh}.speaker .title{font-size:2vw;color:#666;margin-bottom:3vh}.speaker .bio{font-size:1.8vw;color:#555;line-height:1.6}.speaker .session{margin-top:3vh;padding:2vh 2vw;background:#f8f9fa;border-radius:8px;font-size:1.6vw}</style><div class="speaker"><div class="info"><h2>{{label}}</h2><h1>{{name}}</h1><div class="title">{{jobTitle}}</div><div class="bio">{{bio}}</div><div class="session">{{sessionInfo}}</div></div></div>`,
    sampleData: { label: 'Keynote Speaker', name: 'Dr. Sarah Chen', jobTitle: 'Chief Technology Officer — TechCorp', bio: 'Award-winning researcher with 20+ years in artificial intelligence and machine learning.', sessionInfo: 'Session: "The Future of AI in Enterprise" — 9:00 AM, Main Hall' },
  },
  {
    name: 'Venue Map',
    description: 'Event venue layout and directions',
    category: 'events',
    libraryTags: ['venue', 'map', 'directions'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>${baseStyles}.venue{height:100vh;background:#2c3e50;color:#fff;padding:4vw}.venue h1{font-size:3vw;text-align:center;margin-bottom:3vh}.venue .areas{display:grid;grid-template-columns:repeat(2,1fr);gap:2vw}.venue .area{background:#34495e;border-radius:12px;padding:2.5vw}.venue .area h3{font-size:2vw;color:#3498db;margin-bottom:1vh}.venue .area p{font-size:1.5vw;opacity:.8;line-height:1.5}</style><div class="venue"><h1>{{venueName}}</h1><div class="areas"><div class="area"><h3>{{area1}}</h3><p>{{desc1}}</p></div><div class="area"><h3>{{area2}}</h3><p>{{desc2}}</p></div><div class="area"><h3>{{area3}}</h3><p>{{desc3}}</p></div><div class="area"><h3>{{area4}}</h3><p>{{desc4}}</p></div></div></div>`,
    sampleData: { venueName: 'Convention Center', area1: 'Main Hall', desc1: 'Ground floor — Keynotes & panels', area2: 'Workshop Rooms', desc2: 'Second floor — Rooms 201-210', area3: 'Exhibition Hall', desc3: 'East wing — Vendor booths', area4: 'Dining Area', desc4: 'West wing — Breakfast & lunch' },
  },
  {
    name: 'Sponsor Wall',
    description: 'Event sponsors display',
    category: 'events',
    libraryTags: ['sponsors', 'partners', 'acknowledgment'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.sponsors{height:100vh;background:#fff;padding:4vw;display:flex;flex-direction:column;justify-content:center}.sponsors h1{font-size:3vw;text-align:center;color:#2c3e50;margin-bottom:4vh}.sponsors h2{font-size:2vw;text-align:center;color:#999;margin-bottom:2vh}.sponsors .tier{display:flex;justify-content:center;gap:4vw;margin-bottom:3vh;flex-wrap:wrap}.sponsors .name{font-size:2.5vw;color:#2c3e50;font-weight:700}.sponsors .silver .name{font-size:2vw;color:#666}</style><div class="sponsors"><h1>Our Sponsors</h1><h2>{{tierLabel1}}</h2><div class="tier"><span class="name">{{sponsor1}}</span><span class="name">{{sponsor2}}</span></div><h2>{{tierLabel2}}</h2><div class="tier silver"><span class="name">{{sponsor3}}</span><span class="name">{{sponsor4}}</span><span class="name">{{sponsor5}}</span></div></div>`,
    sampleData: { tierLabel1: 'Gold Sponsors', sponsor1: 'TechCorp', sponsor2: 'InnovateCo', tierLabel2: 'Silver Sponsors', sponsor3: 'DataSoft', sponsor4: 'CloudBase', sponsor5: 'NetPro' },
  },
  {
    name: 'Registration Open',
    description: 'Event registration call to action',
    category: 'events',
    libraryTags: ['registration', 'cta', 'signup'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 15,
    templateHtml: `<style>${baseStyles}.register{height:100vh;background:linear-gradient(135deg,#6c5ce7,#fd79a8);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center}.register h1{font-size:4vw;margin-bottom:2vh}.register .event{font-size:2.5vw;opacity:.9;margin-bottom:3vh}.register .cta{font-size:2vw;background:rgba(255,255,255,.2);padding:2vh 4vw;border-radius:50px;display:inline-block}.register .price{font-size:3vw;font-weight:900;margin-bottom:2vh}</style><div class="register"><div><h1>Registration Open</h1><div class="event">{{eventName}} — {{date}}</div><div class="price">{{price}}</div><div class="cta">{{cta}}</div></div></div>`,
    sampleData: { eventName: 'Annual Tech Conference', date: 'April 15-17, 2026', price: 'Early Bird: $199', cta: 'Register at techconf.com' },
  },
  {
    name: 'Live Poll Results',
    description: 'Display live audience poll results',
    category: 'events',
    libraryTags: ['poll', 'live', 'interactive'],
    difficulty: 'advanced',
    templateOrientation: 'landscape',
    duration: 15,
    templateHtml: `<style>${baseStyles}.poll{height:100vh;background:#1a1a2e;color:#fff;padding:4vw}.poll h1{font-size:3vw;text-align:center;margin-bottom:4vh}.poll .option{margin-bottom:2vh}.poll .label{font-size:1.8vw;margin-bottom:1vh;display:flex;justify-content:space-between}.poll .bar-bg{background:#333;border-radius:8px;height:3vh;overflow:hidden}.poll .bar-fill{height:100%;border-radius:8px;background:linear-gradient(90deg,#e94560,#f39c12);transition:width .5s}</style><div class="poll"><h1>{{question}}</h1><div class="option"><div class="label"><span>{{opt1}}</span><span>{{pct1}}</span></div><div class="bar-bg"><div class="bar-fill" style="width:{{pct1}}"></div></div></div><div class="option"><div class="label"><span>{{opt2}}</span><span>{{pct2}}</span></div><div class="bar-bg"><div class="bar-fill" style="width:{{pct2}}"></div></div></div><div class="option"><div class="label"><span>{{opt3}}</span><span>{{pct3}}</span></div><div class="bar-bg"><div class="bar-fill" style="width:{{pct3}}"></div></div></div></div>`,
    sampleData: { question: 'What technology excites you most?', opt1: 'AI / Machine Learning', pct1: '45%', opt2: 'Cloud Computing', pct2: '30%', opt3: 'Blockchain', pct3: '25%' },
  },
  {
    name: 'WiFi Credentials',
    description: 'Event WiFi network information',
    category: 'events',
    libraryTags: ['wifi', 'connectivity', 'info'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 30,
    templateHtml: `<style>${baseStyles}.wifi{height:100vh;background:#2d3436;color:#fff;display:flex;align-items:center;justify-content:center;text-align:center}.wifi h1{font-size:3vw;margin-bottom:4vh}.wifi .cred{font-size:2.5vw;margin-bottom:2vh}.wifi .cred strong{color:#74b9ff}.wifi .note{font-size:1.6vw;opacity:.7;margin-top:3vh}</style><div class="wifi"><div><h1>{{title}}</h1><div class="cred"><strong>Network:</strong> {{network}}</div><div class="cred"><strong>Password:</strong> {{password}}</div><div class="note">{{note}}</div></div></div>`,
    sampleData: { title: 'Free WiFi', network: 'EventGuest-2026', password: 'Welcome2026', note: 'Please do not stream video — bandwidth is shared' },
  },
];

// ============================================================================
// GENERAL TEMPLATES (12)
// ============================================================================
const generalTemplates: TemplateSeed[] = [
  {
    name: 'Welcome Screen',
    description: 'General purpose welcome display',
    category: 'general',
    libraryTags: ['welcome', 'greeting', 'lobby'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 30,
    isFeatured: true,
    templateHtml: `<style>${baseStyles}.welcome{height:100vh;background:linear-gradient(135deg,#667eea,#764ba2);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center}.welcome h1{font-size:5vw;margin-bottom:2vh}.welcome p{font-size:2.5vw;opacity:.9}</style><div class="welcome"><div><h1>{{greeting}}</h1><p>{{subtitle}}</p></div></div>`,
    sampleData: { greeting: 'Welcome', subtitle: 'We are glad to have you here' },
  },
  {
    name: 'Digital Clock',
    description: 'Large format digital clock display',
    category: 'general',
    libraryTags: ['clock', 'time', 'utility'],
    difficulty: 'beginner',
    templateOrientation: 'both',
    duration: 60,
    templateHtml: `<style>${baseStyles}.clock{height:100vh;background:#000;color:#fff;display:flex;align-items:center;justify-content:center;text-align:center}.clock .time{font-size:14vw;font-weight:300;font-family:'Courier New',monospace;letter-spacing:1vw}.clock .date{font-size:3vw;opacity:.6;margin-top:2vh}</style><div class="clock"><div><div class="time">{{time}}</div><div class="date">{{date}}</div></div></div>`,
    sampleData: { time: '10:30 AM', date: 'Saturday, February 8, 2026' },
  },
  {
    name: 'Motivational Quote',
    description: 'Inspirational quote display',
    category: 'general',
    libraryTags: ['quote', 'motivational', 'inspiration'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 15,
    templateHtml: `<style>${baseStyles}.quote{height:100vh;background:#2c3e50;color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;padding:8vw}.quote .text{font-size:3vw;font-style:italic;line-height:1.5;margin-bottom:3vh}.quote .author{font-size:2vw;opacity:.7}</style><div class="quote"><div><div class="text">"{{quote}}"</div><div class="author">— {{author}}</div></div></div>`,
    sampleData: { quote: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
  },
  {
    name: 'Social Media Follow',
    description: 'Social media handles promotion',
    category: 'general',
    libraryTags: ['social', 'follow', 'handles'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.social{height:100vh;background:linear-gradient(135deg,#e1306c,#405de6);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center}.social h1{font-size:4vw;margin-bottom:4vh}.social .handles{font-size:2.5vw;line-height:2.2}</style><div class="social"><div><h1>Follow Us</h1><div class="handles">{{handle1}}<br>{{handle2}}<br>{{handle3}}</div></div></div>`,
    sampleData: { handle1: '@company on Instagram', handle2: '@company on Twitter', handle3: '/company on Facebook' },
  },
  {
    name: 'Contact Information',
    description: 'Business contact details',
    category: 'general',
    libraryTags: ['contact', 'info', 'business'],
    difficulty: 'beginner',
    templateOrientation: 'portrait',
    duration: 30,
    templateHtml: `<style>${baseStyles}.contact{height:100vh;background:#fff;display:flex;align-items:center;justify-content:center;text-align:center;padding:5vw}.contact h1{font-size:3.5vw;color:#2c3e50;margin-bottom:3vh}.contact .info{font-size:2vw;color:#555;line-height:2}</style><div class="contact"><div><h1>{{businessName}}</h1><div class="info">{{phone}}<br>{{email}}<br>{{address}}</div></div></div>`,
    sampleData: { businessName: 'Your Business', phone: '(555) 123-4567', email: 'hello@business.com', address: '123 Main Street, Suite 100' },
  },
  {
    name: 'Announcement Ticker',
    description: 'Scrolling text announcement',
    category: 'general',
    libraryTags: ['ticker', 'scrolling', 'announcement'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.ticker{height:100vh;background:#1a1a2e;display:flex;align-items:center;overflow:hidden}.ticker .text{white-space:nowrap;font-size:5vw;color:#fff;animation:scroll 15s linear infinite}@keyframes scroll{from{transform:translateX(100vw)}to{transform:translateX(-100%)}}</style><div class="ticker"><div class="text">{{message}}</div></div>`,
    sampleData: { message: 'Important: Building maintenance scheduled for this Saturday 8 AM - 12 PM. Please plan accordingly.' },
  },
  {
    name: 'Before & After',
    description: 'Side-by-side comparison display',
    category: 'general',
    libraryTags: ['comparison', 'before-after', 'showcase'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.compare{height:100vh;display:grid;grid-template-columns:1fr 1fr}.compare .side{display:flex;align-items:center;justify-content:center;text-align:center;padding:5vw}.compare .before{background:#e74c3c;color:#fff}.compare .after{background:#27ae60;color:#fff}.compare h2{font-size:3vw;margin-bottom:2vh}.compare p{font-size:2vw;opacity:.9}</style><div class="compare"><div class="side before"><div><h2>Before</h2><p>{{beforeText}}</p></div></div><div class="side after"><div><h2>After</h2><p>{{afterText}}</p></div></div></div>`,
    sampleData: { beforeText: 'Manual processes, paper forms, slow turnaround', afterText: 'Digital workflows, instant updates, 3x faster' },
  },
  {
    name: 'Number Counter',
    description: 'Big number impact display',
    category: 'general',
    libraryTags: ['number', 'stats', 'impact'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 15,
    templateHtml: `<style>${baseStyles}.counter{height:100vh;background:#0984e3;color:#fff;display:flex;align-items:center;justify-content:center;text-align:center}.counter .num{font-size:14vw;font-weight:900}.counter .label{font-size:3vw;opacity:.9;margin-top:2vh}</style><div class="counter"><div><div class="num">{{number}}</div><div class="label">{{label}}</div></div></div>`,
    sampleData: { number: '10,000+', label: 'Customers Served' },
  },
  {
    name: 'Feedback Request',
    description: 'Customer feedback/survey prompt',
    category: 'general',
    libraryTags: ['feedback', 'survey', 'review'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.feedback{height:100vh;background:linear-gradient(135deg,#fdcb6e,#f39c12);color:#333;display:flex;align-items:center;justify-content:center;text-align:center;padding:5vw}.feedback h1{font-size:4vw;margin-bottom:2vh}.feedback p{font-size:2.2vw;margin-bottom:3vh;opacity:.8}.feedback .url{font-size:2.5vw;font-weight:700;background:rgba(255,255,255,.4);padding:1.5vh 3vw;border-radius:8px;display:inline-block}</style><div class="feedback"><div><h1>{{title}}</h1><p>{{message}}</p><div class="url">{{url}}</div></div></div>`,
    sampleData: { title: 'We Value Your Feedback', message: 'Tell us about your experience today', url: 'feedback.company.com' },
  },
  {
    name: 'Photo Gallery',
    description: 'Multi-photo display grid',
    category: 'general',
    libraryTags: ['photos', 'gallery', 'grid'],
    difficulty: 'intermediate',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.gallery{height:100vh;background:#111;padding:1vw;display:grid;grid-template-columns:repeat(3,1fr);grid-template-rows:repeat(2,1fr);gap:1vw}.gallery .photo{background:#333;border-radius:8px;display:flex;align-items:center;justify-content:center;color:#666;font-size:2vw}</style><div class="gallery"><div class="photo">{{caption1}}</div><div class="photo">{{caption2}}</div><div class="photo">{{caption3}}</div><div class="photo">{{caption4}}</div><div class="photo">{{caption5}}</div><div class="photo">{{caption6}}</div></div>`,
    sampleData: { caption1: 'Photo 1', caption2: 'Photo 2', caption3: 'Photo 3', caption4: 'Photo 4', caption5: 'Photo 5', caption6: 'Photo 6' },
  },
  {
    name: 'Tip of the Day',
    description: 'Daily tip or fun fact display',
    category: 'general',
    libraryTags: ['tip', 'fact', 'daily'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 20,
    templateHtml: `<style>${baseStyles}.tip{height:100vh;background:linear-gradient(135deg,#00b894,#00cec9);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center;padding:8vw}.tip h2{font-size:2.5vw;opacity:.9;margin-bottom:2vh}.tip h1{font-size:3.5vw;margin-bottom:3vh}.tip p{font-size:2vw;line-height:1.6;opacity:.9}</style><div class="tip"><div><h2>{{label}}</h2><h1>{{title}}</h1><p>{{content}}</p></div></div>`,
    sampleData: { label: 'Tip of the Day', title: 'Keyboard Shortcuts', content: 'Press Ctrl+Shift+T to reopen the last closed browser tab. Works in Chrome, Firefox, and Edge!' },
  },
  {
    name: 'Thank You Screen',
    description: 'Thank you / closing message',
    category: 'general',
    libraryTags: ['thank-you', 'closing', 'gratitude'],
    difficulty: 'beginner',
    templateOrientation: 'landscape',
    duration: 15,
    templateHtml: `<style>${baseStyles}.thanks{height:100vh;background:linear-gradient(135deg,#667eea,#764ba2);color:#fff;display:flex;align-items:center;justify-content:center;text-align:center}.thanks h1{font-size:6vw;margin-bottom:3vh}.thanks p{font-size:2.5vw;opacity:.9}</style><div class="thanks"><div><h1>{{message}}</h1><p>{{subtitle}}</p></div></div>`,
    sampleData: { message: 'Thank You!', subtitle: 'We appreciate your visit. See you next time!' },
  },
];

// ============================================================================
// EXPORT ALL TEMPLATES
// ============================================================================
export const allTemplateSeeds: TemplateSeed[] = [
  ...retailTemplates,
  ...restaurantTemplates,
  ...corporateTemplates,
  ...educationTemplates,
  ...healthcareTemplates,
  ...eventsTemplates,
  ...generalTemplates,
];

// Category summary for verification
export const categorySummary = {
  retail: retailTemplates.length,
  restaurant: restaurantTemplates.length,
  corporate: corporateTemplates.length,
  education: educationTemplates.length,
  healthcare: healthcareTemplates.length,
  events: eventsTemplates.length,
  general: generalTemplates.length,
  total: allTemplateSeeds.length,
};
